/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Aldo
 */
public class Agente_form extends javax.swing.JFrame {
    
    JTable tabla;
    Connection cnx;
    /**
     * Creates new form Agente_form
     */
    public Agente_form(Connection cnx, JTable t_agentes) {
        initComponents();
        this.cnx=cnx;
        tabla = t_agentes;
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fSLabel1 = new LIB.FSLabel();
        Tf_nombre_codigo = new LIB.FSTexFieldMD();
        fSLabel2 = new LIB.FSLabel();
        fSLabel3 = new LIB.FSLabel();
        fSLabel4 = new LIB.FSLabel();
        fSLabel5 = new LIB.FSLabel();
        Tf_pais = new LIB.FSTexFieldMD();
        Tf_departamento = new LIB.FSTexFieldMD();
        Tf_nombre_agente = new LIB.FSTexFieldMD();
        Tf_usuario = new LIB.FSTexFieldMD();
        Tf_celular = new LIB.FSTexFieldMD();
        fSLabel7 = new LIB.FSLabel();
        fSLabel8 = new LIB.FSLabel();
        Tf_barrio = new LIB.FSTexFieldMD();
        fSLabel9 = new LIB.FSLabel();
        Tf_calle = new LIB.FSTexFieldMD();
        fSButtonMD1 = new LIB.FSButtonMD();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(33, 45, 62));

        fSLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fSLabel1.setText("Código");

        Tf_nombre_codigo.setForeground(new java.awt.Color(73, 181, 172));
        Tf_nombre_codigo.setText("fSTexFieldMD1");
        Tf_nombre_codigo.setBordeColorFocus(new java.awt.Color(73, 181, 172));
        Tf_nombre_codigo.setSelectionColor(new java.awt.Color(73, 181, 172));

        fSLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fSLabel2.setText("Nombre");

        fSLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fSLabel3.setText("País");

        fSLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fSLabel4.setText("Celular");

        fSLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fSLabel5.setText("Usuario");

        Tf_pais.setForeground(new java.awt.Color(73, 181, 172));
        Tf_pais.setText("fSTexFieldMD1");
        Tf_pais.setBordeColorFocus(new java.awt.Color(73, 181, 172));
        Tf_pais.setSelectionColor(new java.awt.Color(73, 181, 172));

        Tf_departamento.setForeground(new java.awt.Color(73, 181, 172));
        Tf_departamento.setText("fSTexFieldMD1");
        Tf_departamento.setBordeColorFocus(new java.awt.Color(73, 181, 172));
        Tf_departamento.setSelectionColor(new java.awt.Color(73, 181, 172));

        Tf_nombre_agente.setForeground(new java.awt.Color(73, 181, 172));
        Tf_nombre_agente.setText("fSTexFieldMD1");
        Tf_nombre_agente.setBordeColorFocus(new java.awt.Color(73, 181, 172));
        Tf_nombre_agente.setSelectionColor(new java.awt.Color(73, 181, 172));

        Tf_usuario.setForeground(new java.awt.Color(73, 181, 172));
        Tf_usuario.setText("fSTexFieldMD1");
        Tf_usuario.setBordeColorFocus(new java.awt.Color(73, 181, 172));
        Tf_usuario.setSelectionColor(new java.awt.Color(73, 181, 172));

        Tf_celular.setForeground(new java.awt.Color(73, 181, 172));
        Tf_celular.setText("fSTexFieldMD1");
        Tf_celular.setBordeColorFocus(new java.awt.Color(73, 181, 172));
        Tf_celular.setSelectionColor(new java.awt.Color(73, 181, 172));

        fSLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fSLabel7.setText("Barrio");

        fSLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fSLabel8.setText("Departamento");

        Tf_barrio.setForeground(new java.awt.Color(73, 181, 172));
        Tf_barrio.setText("fSTexFieldMD1");
        Tf_barrio.setBordeColorFocus(new java.awt.Color(73, 181, 172));
        Tf_barrio.setSelectionColor(new java.awt.Color(73, 181, 172));

        fSLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fSLabel9.setText("Calle");

        Tf_calle.setForeground(new java.awt.Color(73, 181, 172));
        Tf_calle.setText("fSTexFieldMD1");
        Tf_calle.setBordeColorFocus(new java.awt.Color(73, 181, 172));
        Tf_calle.setSelectionColor(new java.awt.Color(73, 181, 172));

        fSButtonMD1.setText("Agregar agente");
        fSButtonMD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fSButtonMD1MouseClicked(evt);
            }
        });
        fSButtonMD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSButtonMD1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fSLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fSLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fSLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fSLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fSLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fSLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Tf_nombre_codigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Tf_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Tf_nombre_agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tf_calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tf_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(fSLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Tf_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fSLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Tf_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(fSButtonMD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_nombre_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_nombre_agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tf_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fSLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(fSButtonMD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fSButtonMD1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fSButtonMD1MouseClicked
        // TODO add your handling code here:
        Agregar_agente();
        Admin_page ad=new Admin_page(cnx);
        DefaultTableModel model =(DefaultTableModel) tabla.getModel();
        model.setRowCount(0);
        ad.llenar_tabla(9, tabla, "CALL SHOW_AGENTE()");
    }//GEN-LAST:event_fSButtonMD1MouseClicked

    private void fSButtonMD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSButtonMD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fSButtonMD1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
        private void Agregar_agente(){
        
        try {
            String sql = " CALL INSERTAR_AGENTE (?,?,?,?,?,?,?,?,?)";
            
            PreparedStatement sentencia= cnx.prepareStatement(sql);
            sentencia.setInt(1, Integer.parseInt (Tf_nombre_codigo.getText()));
            sentencia.setString(2, Tf_nombre_agente.getText());
            sentencia.setString(3,Tf_usuario.getText());
            sentencia.setString(4,Tf_pais.getText());
            sentencia.setString(5,Tf_departamento.getText());
            sentencia.setString(6,Tf_barrio.getText());
            sentencia.setString(7,Tf_calle.getText());
            sentencia.setDate(8,new java.sql.Date((System.currentTimeMillis())));
            sentencia.setString(9,Tf_celular.getText());

            sentencia.executeUpdate();
            
            System.out.println("Inserción de agente con exito");
        } catch (SQLException ex) {
            Logger.getLogger(Cl_form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSTexFieldMD Tf_barrio;
    private LIB.FSTexFieldMD Tf_calle;
    private LIB.FSTexFieldMD Tf_celular;
    private LIB.FSTexFieldMD Tf_departamento;
    private LIB.FSTexFieldMD Tf_nombre_agente;
    private LIB.FSTexFieldMD Tf_nombre_codigo;
    private LIB.FSTexFieldMD Tf_pais;
    private LIB.FSTexFieldMD Tf_usuario;
    private LIB.FSButtonMD fSButtonMD1;
    private LIB.FSLabel fSLabel1;
    private LIB.FSLabel fSLabel2;
    private LIB.FSLabel fSLabel3;
    private LIB.FSLabel fSLabel4;
    private LIB.FSLabel fSLabel5;
    private LIB.FSLabel fSLabel7;
    private LIB.FSLabel fSLabel8;
    private LIB.FSLabel fSLabel9;
    // End of variables declaration//GEN-END:variables
}
