/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.*;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import java.time.*;
import java.sql.Date;
import static java.time.Instant.now;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
/**
 *
 * @author Aldo
 */
public class Cl_compra_form_1 extends javax.swing.JFrame {
    
    public Connection cnx;
    public JTable TablaClientes;
    public int fila;
    /**
     * Creates new form Cl_form
     */
    public Cl_compra_form_1 (Connection cnx, JTable Tabla, int fila) {
        initComponents();
        this.cnx = cnx;
        this.TablaClientes= Tabla;
        this.fila = fila;
        DateTimeFormatter dtf5 = DateTimeFormatter.ofPattern("yyyy/MM/dd hh:mm");
        Tf_fecha_compra.setText((dtf5.format(LocalDateTime.now())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fSTexFieldMD1 = new LIB.FSTexFieldMD();
        B_agregar_compra = new LIB.FSButtonMD();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelRound1 = new LIB.JPanelRound();
        Tf_unidades = new LIB.FSTexFieldMD();
        fSLabel13 = new LIB.FSLabel();
        fSLabel16 = new LIB.FSLabel();
        Tf_total = new LIB.FSTexFieldMD();
        fSLabel17 = new LIB.FSLabel();
        Tf_iva_factura = new LIB.FSTexFieldMD();
        fSLabel18 = new LIB.FSLabel();
        Tf_fecha_compra = new LIB.FSTexFieldMD();
        fSLabel19 = new LIB.FSLabel();
        Tfcantidad = new LIB.FSTexFieldMD();
        fSLabel20 = new LIB.FSLabel();
        Tf_subtotal = new LIB.FSTexFieldMD();
        fSLabel21 = new LIB.FSLabel();
        Tf_precio_unitario = new LIB.FSTexFieldMD();
        Tf_id_producto = new LIB.FSTexFieldMD();
        fSLabel1 = new LIB.FSLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fSLabel24 = new LIB.FSLabel();

        fSTexFieldMD1.setText("fSTexFieldMD1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B_agregar_compra.setBackground(new java.awt.Color(0, 153, 153));
        B_agregar_compra.setText("Agregar compra");
        B_agregar_compra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_agregar_compraMouseClicked(evt);
            }
        });
        B_agregar_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_agregar_compraActionPerformed(evt);
            }
        });

        jPanelRound1.setBackground(new java.awt.Color(33, 45, 62));

        Tf_unidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_unidadesActionPerformed(evt);
            }
        });

        fSLabel13.setBorder(null);
        fSLabel13.setText("Tótal de unidades compradas");

        fSLabel16.setBorder(null);
        fSLabel16.setText("Valor tótal factura");

        Tf_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_totalActionPerformed(evt);
            }
        });

        fSLabel17.setBorder(null);
        fSLabel17.setText("Iva factura");

        Tf_iva_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_iva_facturaActionPerformed(evt);
            }
        });

        fSLabel18.setBorder(null);
        fSLabel18.setText("Fecha de compra");

        Tf_fecha_compra.setEditable(false);
        Tf_fecha_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_fecha_compraActionPerformed(evt);
            }
        });

        fSLabel19.setBorder(null);
        fSLabel19.setText("Cantidad ");

        Tfcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfcantidadActionPerformed(evt);
            }
        });

        fSLabel20.setBorder(null);
        fSLabel20.setText("Subtotal");

        Tf_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_subtotalActionPerformed(evt);
            }
        });

        fSLabel21.setBorder(null);
        fSLabel21.setText("Precio unitario");

        Tf_precio_unitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_precio_unitarioActionPerformed(evt);
            }
        });

        Tf_id_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_id_productoActionPerformed(evt);
            }
        });

        fSLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        fSLabel1.setText("Información de factura");

        jSeparator1.setBackground(new java.awt.Color(0, 255, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        fSLabel24.setBorder(null);
        fSLabel24.setText("Id de producto ");

        javax.swing.GroupLayout jPanelRound1Layout = new javax.swing.GroupLayout(jPanelRound1);
        jPanelRound1.setLayout(jPanelRound1Layout);
        jPanelRound1Layout.setHorizontalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 435, Short.MAX_VALUE))
                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                        .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelRound1Layout.createSequentialGroup()
                                    .addComponent(fSLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Tf_precio_unitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelRound1Layout.createSequentialGroup()
                                    .addComponent(fSLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Tf_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelRound1Layout.createSequentialGroup()
                                    .addComponent(fSLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Tfcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelRound1Layout.createSequentialGroup()
                                    .addComponent(fSLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Tf_fecha_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelRound1Layout.createSequentialGroup()
                                    .addComponent(fSLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Tf_iva_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelRound1Layout.createSequentialGroup()
                                    .addComponent(fSLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Tf_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelRound1Layout.createSequentialGroup()
                                    .addComponent(fSLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound1Layout.createSequentialGroup()
                                .addComponent(fSLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137)))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                        .addComponent(fSLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tf_id_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(418, 418, 418))
        );
        jPanelRound1Layout.setVerticalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fSLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_iva_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_fecha_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tfcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fSLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_precio_unitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_id_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanelRound1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(B_agregar_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_agregar_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_agregar_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_agregar_compraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_agregar_compraActionPerformed

    private void B_agregar_compraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_agregar_compraMouseClicked
        // TODO add your handling code here:
        PreparedStatement insert;
        
        /*
        String actividad = Tf_actividad_principal.getText();
        String canal = Tf_canal.getText();
        String intro = Tf_intro.getText();
        String nombre_comercial = Tf_nombre_comercial.getText();
        int tiempo = Integer.parseInt (Tf_tiempo.getText());
        String tipo = Tf_tipo.getText();
        String web = Tf_web.getText();
        String barrio = Tfbarrio.getText();
        String calle = Tfcalle.getText();
        int capacidad = Integer.parseInt (Tfcapacidad.getText());
        String cel = Tfcel.getText();
        String ciudad = Tfciudad.getText();
        String correo = Tfcorreo_principal.getText();
        String correo_2 =Tfcorreo_secundario.getText();
        String departamento = Tfdepartamento.getText();
        int indicativo =Integer.parseInt (Tfindicativo.getText());
        String linea = Tflinea.getText();
        String marca = Tfmarca.getText();
        String pais = Tfpais.getText();
        String proveedor = Tfproveedor_principal.getText();
        int sucursales =Integer.parseInt (Tfsucursales.getText());
        */
        
        try {
            String sql = "CALL INSERT_COMPRA_CLIENTE_CONSOLIDADO(?,?,?,?,?,?,?,?,?)";
            
            PreparedStatement sentencia= cnx.prepareStatement(sql);
            sentencia.setInt(1,(int) TablaClientes.getValueAt(fila, 0)); 
            sentencia.setInt(2,Integer.parseInt (Tf_unidades.getText()));
            sentencia.setDouble(3,Integer.parseInt (Tf_total.getText()));
            sentencia.setDouble(4,Integer.parseInt (Tf_iva_factura.getText()));
            sentencia.setDate(5,new java.sql.Date((System.currentTimeMillis())));
            sentencia.setInt(6,Integer.parseInt (Tfcantidad.getText()));
            sentencia.setDouble(7,Integer.parseInt (Tf_subtotal.getText()));
            sentencia.setDouble(8,Integer.parseInt (Tf_precio_unitario.getText()));
            sentencia.setInt(9,Integer.parseInt (Tf_id_producto.getText()));
            
            sentencia.executeUpdate();
            
            System.out.println("Inserción de compra con exito");
                       
            JOptionPane.showMessageDialog(null, "Compra agregada con exito.");
        } catch (SQLException ex) {
            Logger.getLogger(Cl_compra_form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_B_agregar_compraMouseClicked

    private void Tf_id_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_id_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_id_productoActionPerformed

    private void Tf_precio_unitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_precio_unitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_precio_unitarioActionPerformed

    private void Tf_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_subtotalActionPerformed

    private void TfcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfcantidadActionPerformed

    private void Tf_fecha_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_fecha_compraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_fecha_compraActionPerformed

    private void Tf_iva_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_iva_facturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_iva_facturaActionPerformed

    private void Tf_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_totalActionPerformed

    private void Tf_unidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_unidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_unidadesActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD B_agregar_compra;
    private LIB.FSTexFieldMD Tf_fecha_compra;
    private LIB.FSTexFieldMD Tf_id_producto;
    private LIB.FSTexFieldMD Tf_iva_factura;
    private LIB.FSTexFieldMD Tf_precio_unitario;
    private LIB.FSTexFieldMD Tf_subtotal;
    private LIB.FSTexFieldMD Tf_total;
    private LIB.FSTexFieldMD Tf_unidades;
    private LIB.FSTexFieldMD Tfcantidad;
    private LIB.FSLabel fSLabel1;
    private LIB.FSLabel fSLabel13;
    private LIB.FSLabel fSLabel16;
    private LIB.FSLabel fSLabel17;
    private LIB.FSLabel fSLabel18;
    private LIB.FSLabel fSLabel19;
    private LIB.FSLabel fSLabel20;
    private LIB.FSLabel fSLabel21;
    private LIB.FSLabel fSLabel24;
    private LIB.FSTexFieldMD fSTexFieldMD1;
    private LIB.JPanelRound jPanelRound1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
