/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.*;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import java.time.*;
import java.sql.Date;
import static java.time.Instant.now;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
/**
 *
 * @author Aldo
 */
public class Cl_compra_form extends javax.swing.JFrame {
    
    public Connection cnx;
    public JTable TablaClientes;
    public int fila;
    

    /**
     * Creates new form Cl_form
     */
    public Cl_compra_form(Connection cnx, JTable Tabla, int fila) {
        initComponents();
        this.cnx = cnx;
        this.TablaClientes= Tabla;
        this.fila = fila;
        DateTimeFormatter dtf5 = DateTimeFormatter.ofPattern("yyyy/MM/dd hh:mm");
        Tf_fecha_compra.setText((dtf5.format(LocalDateTime.now())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fSTexFieldMD1 = new LIB.FSTexFieldMD();
        B_agregar_compra = new LIB.FSButtonMD();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelRound1 = new LIB.JPanelRound();
        fSLabel2 = new LIB.FSLabel();
        Tf_calificacion = new LIB.FSTexFieldMD();
        fSLabel3 = new LIB.FSLabel();
        Tf_extracupo = new LIB.FSTexFieldMD();
        fSLabel4 = new LIB.FSLabel();
        Tf_credito = new LIB.FSTexFieldMD();
        fSLabel5 = new LIB.FSLabel();
        Tf_cupo = new LIB.FSTexFieldMD();
        Tf_total_debito = new LIB.FSTexFieldMD();
        fSLabel6 = new LIB.FSLabel();
        Tf_total_credito = new LIB.FSTexFieldMD();
        fSLabel7 = new LIB.FSLabel();
        Tf_aseguradora = new LIB.FSTexFieldMD();
        fSLabel8 = new LIB.FSLabel();
        Tfproveedor_pais_secundariol = new LIB.FSTexFieldMD();
        fSLabel9 = new LIB.FSLabel();
        Tf_ciudad = new LIB.FSTexFieldMD();
        fSLabel10 = new LIB.FSLabel();
        Tf_barrio = new LIB.FSTexFieldMD();
        fSLabel11 = new LIB.FSLabel();
        Tf_calle = new LIB.FSTexFieldMD();
        fSLabel12 = new LIB.FSLabel();
        Tf_unidades = new LIB.FSTexFieldMD();
        fSLabel13 = new LIB.FSLabel();
        fSLabel14 = new LIB.FSLabel();
        Tf_iva = new LIB.FSTexFieldMD();
        fSLabel15 = new LIB.FSLabel();
        Tf_codigo_vendedor = new LIB.FSTexFieldMD();
        fSLabel16 = new LIB.FSLabel();
        Tf_total = new LIB.FSTexFieldMD();
        fSLabel17 = new LIB.FSLabel();
        Tf_iva_factura = new LIB.FSTexFieldMD();
        fSLabel18 = new LIB.FSLabel();
        Tf_fecha_compra = new LIB.FSTexFieldMD();
        fSLabel19 = new LIB.FSLabel();
        Tfcantidad = new LIB.FSTexFieldMD();
        fSLabel20 = new LIB.FSLabel();
        Tf_subtotal = new LIB.FSTexFieldMD();
        fSLabel21 = new LIB.FSLabel();
        Tf_precio_unitario = new LIB.FSTexFieldMD();
        Tf_id_producto = new LIB.FSTexFieldMD();
        fSLabel1 = new LIB.FSLabel();
        fSLabel23 = new LIB.FSLabel();
        fSLabel24 = new LIB.FSLabel();

        fSTexFieldMD1.setText("fSTexFieldMD1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B_agregar_compra.setBackground(new java.awt.Color(0, 153, 153));
        B_agregar_compra.setText("Agregar compra");
        B_agregar_compra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_agregar_compraMouseClicked(evt);
            }
        });
        B_agregar_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_agregar_compraActionPerformed(evt);
            }
        });

        jPanelRound1.setBackground(new java.awt.Color(33, 45, 62));
        jPanelRound1.setLayout(null);

        fSLabel2.setBorder(null);
        fSLabel2.setText("Calificación cliente");
        jPanelRound1.add(fSLabel2);
        fSLabel2.setBounds(29, 175, 184, 42);

        Tf_calificacion.setForeground(new java.awt.Color(73, 181, 172));
        Tf_calificacion.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        Tf_calificacion.setSoloLetras(true);
        Tf_calificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_calificacionActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_calificacion);
        Tf_calificacion.setBounds(223, 176, 250, 42);

        fSLabel3.setBorder(null);
        fSLabel3.setText("Extracupo");
        jPanelRound1.add(fSLabel3);
        fSLabel3.setBounds(29, 229, 184, 42);

        Tf_extracupo.setForeground(new java.awt.Color(73, 181, 172));
        Tf_extracupo.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        Tf_extracupo.setSoloNumeros(true);
        Tf_extracupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_extracupoActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_extracupo);
        Tf_extracupo.setBounds(223, 230, 250, 42);

        fSLabel4.setBorder(null);
        fSLabel4.setText("Crédito");
        jPanelRound1.add(fSLabel4);
        fSLabel4.setBounds(29, 283, 184, 42);

        Tf_credito.setForeground(new java.awt.Color(73, 181, 172));
        Tf_credito.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        Tf_credito.setSoloNumeros(true);
        Tf_credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_creditoActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_credito);
        Tf_credito.setBounds(223, 284, 250, 42);

        fSLabel5.setBorder(null);
        fSLabel5.setText("Cupo");
        jPanelRound1.add(fSLabel5);
        fSLabel5.setBounds(29, 332, 184, 42);

        Tf_cupo.setForeground(new java.awt.Color(73, 181, 172));
        Tf_cupo.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        Tf_cupo.setSoloNumeros(true);
        Tf_cupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_cupoActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_cupo);
        Tf_cupo.setBounds(223, 333, 250, 42);

        Tf_total_debito.setSoloNumeros(true);
        Tf_total_debito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_total_debitoActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_total_debito);
        Tf_total_debito.setBounds(223, 387, 250, 42);

        fSLabel6.setBorder(null);
        fSLabel6.setText("Tótal débito");
        jPanelRound1.add(fSLabel6);
        fSLabel6.setBounds(29, 386, 184, 42);

        Tf_total_credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_total_creditoActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_total_credito);
        Tf_total_credito.setBounds(223, 436, 250, 42);

        fSLabel7.setBorder(null);
        fSLabel7.setText("Total crédito");
        jPanelRound1.add(fSLabel7);
        fSLabel7.setBounds(29, 435, 184, 42);

        Tf_aseguradora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_aseguradoraActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_aseguradora);
        Tf_aseguradora.setBounds(223, 485, 250, 42);

        fSLabel8.setBorder(null);
        fSLabel8.setText("Aseguradora");
        jPanelRound1.add(fSLabel8);
        fSLabel8.setBounds(29, 484, 184, 42);

        Tfproveedor_pais_secundariol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tfproveedor_pais_secundariolActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tfproveedor_pais_secundariol);
        Tfproveedor_pais_secundariol.setBounds(223, 534, 250, 42);

        fSLabel9.setBorder(null);
        fSLabel9.setText("Pais secundario");
        jPanelRound1.add(fSLabel9);
        fSLabel9.setBounds(29, 533, 184, 42);

        Tf_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_ciudadActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_ciudad);
        Tf_ciudad.setBounds(223, 584, 250, 42);

        fSLabel10.setBorder(null);
        fSLabel10.setText("Ciudad secundaria");
        jPanelRound1.add(fSLabel10);
        fSLabel10.setBounds(29, 583, 184, 42);

        Tf_barrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_barrioActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_barrio);
        Tf_barrio.setBounds(223, 633, 250, 42);

        fSLabel11.setBorder(null);
        fSLabel11.setText("Barrio secundario");
        jPanelRound1.add(fSLabel11);
        fSLabel11.setBounds(29, 632, 184, 42);

        Tf_calle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_calleActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_calle);
        Tf_calle.setBounds(223, 687, 250, 42);

        fSLabel12.setBorder(null);
        fSLabel12.setText("Calle secundaria");
        jPanelRound1.add(fSLabel12);
        fSLabel12.setBounds(29, 686, 184, 42);

        Tf_unidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_unidadesActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_unidades);
        Tf_unidades.setBounds(710, 80, 250, 42);

        fSLabel13.setBorder(null);
        fSLabel13.setText("Tótal de unidades compradas");
        jPanelRound1.add(fSLabel13);
        fSLabel13.setBounds(510, 80, 184, 42);

        fSLabel14.setBorder(null);
        fSLabel14.setText("Iva de cliente consolidado");
        jPanelRound1.add(fSLabel14);
        fSLabel14.setBounds(29, 126, 184, 42);

        Tf_iva.setForeground(new java.awt.Color(73, 181, 172));
        Tf_iva.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        Tf_iva.setSoloNumeros(true);
        Tf_iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_ivaActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_iva);
        Tf_iva.setBounds(223, 127, 250, 42);

        fSLabel15.setBorder(null);
        fSLabel15.setText("Código vendedor");
        jPanelRound1.add(fSLabel15);
        fSLabel15.setBounds(29, 80, 184, 42);

        Tf_codigo_vendedor.setForeground(new java.awt.Color(73, 181, 172));
        Tf_codigo_vendedor.setBordeColorFocus(new java.awt.Color(73, 181, 172));
        Tf_codigo_vendedor.setSoloNumeros(true);
        Tf_codigo_vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_codigo_vendedorActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_codigo_vendedor);
        Tf_codigo_vendedor.setBounds(223, 81, 250, 42);

        fSLabel16.setBorder(null);
        fSLabel16.setText("Valor tótal factura");
        jPanelRound1.add(fSLabel16);
        fSLabel16.setBounds(510, 130, 184, 42);

        Tf_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_totalActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_total);
        Tf_total.setBounds(710, 130, 250, 42);

        fSLabel17.setBorder(null);
        fSLabel17.setText("Iva factura");
        jPanelRound1.add(fSLabel17);
        fSLabel17.setBounds(510, 180, 184, 42);

        Tf_iva_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_iva_facturaActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_iva_factura);
        Tf_iva_factura.setBounds(710, 180, 250, 42);

        fSLabel18.setBorder(null);
        fSLabel18.setText("Fecha de compra");
        jPanelRound1.add(fSLabel18);
        fSLabel18.setBounds(510, 230, 184, 42);

        Tf_fecha_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_fecha_compraActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_fecha_compra);
        Tf_fecha_compra.setBounds(710, 230, 250, 42);

        fSLabel19.setBorder(null);
        fSLabel19.setText("Cantidad ");
        jPanelRound1.add(fSLabel19);
        fSLabel19.setBounds(510, 280, 184, 42);

        Tfcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfcantidadActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tfcantidad);
        Tfcantidad.setBounds(710, 280, 250, 42);

        fSLabel20.setBorder(null);
        fSLabel20.setText("Subtotal");
        jPanelRound1.add(fSLabel20);
        fSLabel20.setBounds(510, 330, 184, 42);

        Tf_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_subtotalActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_subtotal);
        Tf_subtotal.setBounds(710, 330, 250, 42);

        fSLabel21.setBorder(null);
        fSLabel21.setText("Precio unitario");
        jPanelRound1.add(fSLabel21);
        fSLabel21.setBounds(510, 380, 184, 42);

        Tf_precio_unitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_precio_unitarioActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_precio_unitario);
        Tf_precio_unitario.setBounds(710, 380, 250, 42);

        Tf_id_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_id_productoActionPerformed(evt);
            }
        });
        jPanelRound1.add(Tf_id_producto);
        Tf_id_producto.setBounds(710, 440, 250, 42);

        fSLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        fSLabel1.setText("Información de factura");
        jPanelRound1.add(fSLabel1);
        fSLabel1.setBounds(600, 30, 209, 34);

        fSLabel23.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        fSLabel23.setText("Información del cliente");
        jPanelRound1.add(fSLabel23);
        fSLabel23.setBounds(123, 21, 209, 34);

        fSLabel24.setBorder(null);
        fSLabel24.setText("Id de producto ");
        jPanelRound1.add(fSLabel24);
        fSLabel24.setBounds(510, 440, 184, 42);

        jScrollPane1.setViewportView(jPanelRound1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(B_agregar_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_agregar_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_agregar_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_agregar_compraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_agregar_compraActionPerformed

    private void B_agregar_compraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_agregar_compraMouseClicked
        // TODO add your handling code here:
        PreparedStatement insert;

        
        try {
            String sql = "CALL INSERT_COMPRA(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            // OBTENER VALORES DE LA FILA DE CLIENTES
               
            PreparedStatement sentencia= cnx.prepareStatement(sql);
            sentencia.setInt(1,(int) this.TablaClientes.getValueAt(fila, 0));
            sentencia.setInt(2,Integer.parseInt (Tf_codigo_vendedor.getText()));
            sentencia.setDouble(3,Integer.parseInt (Tf_iva.getText()));
            sentencia.setString(4, Tf_calificacion.getText());
            sentencia.setDouble(5,Integer.parseInt (Tf_extracupo.getText()));
            sentencia.setString(6, Tf_credito.getText());
            sentencia.setDouble(7,Integer.parseInt (Tf_cupo.getText()));
            sentencia.setDouble(8,Integer.parseInt (Tf_total_debito.getText()));
            sentencia.setDouble(9,Integer.parseInt (Tf_total_credito.getText()));
            sentencia.setString(10, Tf_aseguradora.getText());
            sentencia.setString(11, Tfproveedor_pais_secundariol.getText());
            sentencia.setString(12, Tf_ciudad.getText());
            sentencia.setString(13, Tf_barrio.getText());
            sentencia.setString(14, Tf_calle.getText());     
            sentencia.setInt(15,Integer.parseInt (Tf_unidades.getText()));
            sentencia.setDouble(16,Integer.parseInt (Tf_total.getText()));
            sentencia.setDouble(17,Integer.parseInt (Tf_iva_factura.getText()));
            sentencia.setDate(18,new java.sql.Date((System.currentTimeMillis())));
            sentencia.setInt(19,Integer.parseInt (Tfcantidad.getText()));
            sentencia.setDouble(20,Integer.parseInt (Tf_subtotal.getText()));
            sentencia.setDouble(21,Integer.parseInt (Tf_precio_unitario.getText()));
            sentencia.setInt(22,Integer.parseInt (Tf_id_producto.getText()));
            
            sentencia.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Compra agregada con éxito.");
            System.out.println("Inserción de compra con exito");
        } catch (SQLException ex) {
            Logger.getLogger(Cl_compra_form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_B_agregar_compraMouseClicked

    private void Tf_id_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_id_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_id_productoActionPerformed

    private void Tf_precio_unitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_precio_unitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_precio_unitarioActionPerformed

    private void Tf_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_subtotalActionPerformed

    private void TfcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfcantidadActionPerformed

    private void Tf_fecha_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_fecha_compraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_fecha_compraActionPerformed

    private void Tf_iva_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_iva_facturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_iva_facturaActionPerformed

    private void Tf_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_totalActionPerformed

    private void Tf_codigo_vendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_codigo_vendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_codigo_vendedorActionPerformed

    private void Tf_ivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_ivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_ivaActionPerformed

    private void Tf_unidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_unidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_unidadesActionPerformed

    private void Tf_calleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_calleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_calleActionPerformed

    private void Tf_barrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_barrioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_barrioActionPerformed

    private void Tf_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_ciudadActionPerformed

    private void Tfproveedor_pais_secundariolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tfproveedor_pais_secundariolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tfproveedor_pais_secundariolActionPerformed

    private void Tf_aseguradoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_aseguradoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_aseguradoraActionPerformed

    private void Tf_total_creditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_total_creditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_total_creditoActionPerformed

    private void Tf_total_debitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_total_debitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_total_debitoActionPerformed

    private void Tf_cupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_cupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_cupoActionPerformed

    private void Tf_creditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_creditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_creditoActionPerformed

    private void Tf_extracupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_extracupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_extracupoActionPerformed

    private void Tf_calificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_calificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_calificacionActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD B_agregar_compra;
    private LIB.FSTexFieldMD Tf_aseguradora;
    private LIB.FSTexFieldMD Tf_barrio;
    private LIB.FSTexFieldMD Tf_calificacion;
    private LIB.FSTexFieldMD Tf_calle;
    private LIB.FSTexFieldMD Tf_ciudad;
    private LIB.FSTexFieldMD Tf_codigo_vendedor;
    private LIB.FSTexFieldMD Tf_credito;
    private LIB.FSTexFieldMD Tf_cupo;
    private LIB.FSTexFieldMD Tf_extracupo;
    private LIB.FSTexFieldMD Tf_fecha_compra;
    private LIB.FSTexFieldMD Tf_id_producto;
    private LIB.FSTexFieldMD Tf_iva;
    private LIB.FSTexFieldMD Tf_iva_factura;
    private LIB.FSTexFieldMD Tf_precio_unitario;
    private LIB.FSTexFieldMD Tf_subtotal;
    private LIB.FSTexFieldMD Tf_total;
    private LIB.FSTexFieldMD Tf_total_credito;
    private LIB.FSTexFieldMD Tf_total_debito;
    private LIB.FSTexFieldMD Tf_unidades;
    private LIB.FSTexFieldMD Tfcantidad;
    private LIB.FSTexFieldMD Tfproveedor_pais_secundariol;
    private LIB.FSLabel fSLabel1;
    private LIB.FSLabel fSLabel10;
    private LIB.FSLabel fSLabel11;
    private LIB.FSLabel fSLabel12;
    private LIB.FSLabel fSLabel13;
    private LIB.FSLabel fSLabel14;
    private LIB.FSLabel fSLabel15;
    private LIB.FSLabel fSLabel16;
    private LIB.FSLabel fSLabel17;
    private LIB.FSLabel fSLabel18;
    private LIB.FSLabel fSLabel19;
    private LIB.FSLabel fSLabel2;
    private LIB.FSLabel fSLabel20;
    private LIB.FSLabel fSLabel21;
    private LIB.FSLabel fSLabel23;
    private LIB.FSLabel fSLabel24;
    private LIB.FSLabel fSLabel3;
    private LIB.FSLabel fSLabel4;
    private LIB.FSLabel fSLabel5;
    private LIB.FSLabel fSLabel6;
    private LIB.FSLabel fSLabel7;
    private LIB.FSLabel fSLabel8;
    private LIB.FSLabel fSLabel9;
    private LIB.FSTexFieldMD fSTexFieldMD1;
    private LIB.JPanelRound jPanelRound1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
