/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.sql.*;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aldo
 */
public class Cl_form extends javax.swing.JFrame {
    
    private JTable t_clientes;
    private Connection cnx;

    /**
     * Creates new form Cl_form
     */
    public Cl_form(Connection cnx) {
        initComponents();
        this.cnx = cnx;
    }
     
    public Cl_form(Connection cnx, JTable clientes) {
        initComponents();
        this.cnx = cnx;
        this.t_clientes = clientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fSTexFieldMD1 = new LIB.FSTexFieldMD();
        fSButtonMD1 = new LIB.FSButtonMD();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelRound1 = new LIB.JPanelRound();
        fSLabel2 = new LIB.FSLabel();
        Tf_web = new LIB.FSTexFieldMD();
        fSLabel3 = new LIB.FSLabel();
        Tf_tiempo = new LIB.FSTexFieldMD();
        fSLabel4 = new LIB.FSLabel();
        Tfcorreo_principal = new LIB.FSTexFieldMD();
        fSLabel5 = new LIB.FSLabel();
        Tfcorreo_secundario = new LIB.FSTexFieldMD();
        Tf_tipo = new LIB.FSTexFieldMD();
        fSLabel6 = new LIB.FSLabel();
        Tf_actividad_principal = new LIB.FSTexFieldMD();
        fSLabel7 = new LIB.FSLabel();
        Tf_intro = new LIB.FSTexFieldMD();
        fSLabel8 = new LIB.FSLabel();
        Tfproveedor_principal = new LIB.FSTexFieldMD();
        fSLabel9 = new LIB.FSLabel();
        Tfindicativo = new LIB.FSTexFieldMD();
        fSLabel10 = new LIB.FSLabel();
        Tfcel = new LIB.FSTexFieldMD();
        fSLabel11 = new LIB.FSLabel();
        Tfpais = new LIB.FSTexFieldMD();
        fSLabel12 = new LIB.FSLabel();
        Tfdepartamento = new LIB.FSTexFieldMD();
        fSLabel13 = new LIB.FSLabel();
        fSLabel14 = new LIB.FSLabel();
        Tf_canal = new LIB.FSTexFieldMD();
        fSLabel15 = new LIB.FSLabel();
        Tf_nombre_comercial = new LIB.FSTexFieldMD();
        fSLabel16 = new LIB.FSLabel();
        Tfciudad = new LIB.FSTexFieldMD();
        fSLabel17 = new LIB.FSLabel();
        Tfbarrio = new LIB.FSTexFieldMD();
        fSLabel18 = new LIB.FSLabel();
        Tfcalle = new LIB.FSTexFieldMD();
        fSLabel19 = new LIB.FSLabel();
        Tfcapacidad = new LIB.FSTexFieldMD();
        fSLabel20 = new LIB.FSLabel();
        Tflinea = new LIB.FSTexFieldMD();
        fSLabel21 = new LIB.FSLabel();
        Tfmarca = new LIB.FSTexFieldMD();
        fSLabel22 = new LIB.FSLabel();
        Tfsucursales = new LIB.FSTexFieldMD();

        fSTexFieldMD1.setText("fSTexFieldMD1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        fSButtonMD1.setBackground(new java.awt.Color(0, 153, 153));
        fSButtonMD1.setText("Ingresar Cliente");
        fSButtonMD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fSButtonMD1MouseClicked(evt);
            }
        });
        fSButtonMD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSButtonMD1ActionPerformed(evt);
            }
        });

        jPanelRound1.setBackground(new java.awt.Color(33, 45, 62));

        fSLabel2.setBorder(null);
        fSLabel2.setText("Website");

        Tf_web.setForeground(new java.awt.Color(73, 181, 172));
        Tf_web.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        Tf_web.setSoloLetras(true);
        Tf_web.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_webActionPerformed(evt);
            }
        });

        fSLabel3.setBorder(null);
        fSLabel3.setText("Tiempo en el mercado");

        Tf_tiempo.setForeground(new java.awt.Color(73, 181, 172));
        Tf_tiempo.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        Tf_tiempo.setSoloNumeros(true);
        Tf_tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_tiempoActionPerformed(evt);
            }
        });

        fSLabel4.setBorder(null);
        fSLabel4.setText("Correo principal");

        Tfcorreo_principal.setForeground(new java.awt.Color(73, 181, 172));
        Tfcorreo_principal.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        Tfcorreo_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tfcorreo_principalActionPerformed(evt);
            }
        });

        fSLabel5.setBorder(null);
        fSLabel5.setText("Correo secundario");

        Tfcorreo_secundario.setForeground(new java.awt.Color(73, 181, 172));
        Tfcorreo_secundario.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        Tfcorreo_secundario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tfcorreo_secundarioActionPerformed(evt);
            }
        });

        Tf_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_tipoActionPerformed(evt);
            }
        });

        fSLabel6.setBorder(null);
        fSLabel6.setText("Tipo de cliente");

        Tf_actividad_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_actividad_principalActionPerformed(evt);
            }
        });

        fSLabel7.setBorder(null);
        fSLabel7.setText("Actividad principal");

        Tf_intro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_introActionPerformed(evt);
            }
        });

        fSLabel8.setBorder(null);
        fSLabel8.setText("Introducción");

        Tfproveedor_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tfproveedor_principalActionPerformed(evt);
            }
        });

        fSLabel9.setBorder(null);
        fSLabel9.setText("Proveedor principal");

        Tfindicativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfindicativoActionPerformed(evt);
            }
        });

        fSLabel10.setBorder(null);
        fSLabel10.setText("Indicativo");

        Tfcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfcelActionPerformed(evt);
            }
        });

        fSLabel11.setBorder(null);
        fSLabel11.setText("Celular");

        Tfpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfpaisActionPerformed(evt);
            }
        });

        fSLabel12.setBorder(null);
        fSLabel12.setText("Pais");

        Tfdepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfdepartamentoActionPerformed(evt);
            }
        });

        fSLabel13.setBorder(null);
        fSLabel13.setText("Departamento");

        fSLabel14.setBorder(null);
        fSLabel14.setText("Canal de venta");

        Tf_canal.setForeground(new java.awt.Color(73, 181, 172));
        Tf_canal.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        Tf_canal.setSoloLetras(true);
        Tf_canal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_canalActionPerformed(evt);
            }
        });

        fSLabel15.setBorder(null);
        fSLabel15.setText("Nombre comercial");

        Tf_nombre_comercial.setForeground(new java.awt.Color(73, 181, 172));
        Tf_nombre_comercial.setBordeColorFocus(new java.awt.Color(73, 181, 172));
        Tf_nombre_comercial.setSoloLetras(true);
        Tf_nombre_comercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_nombre_comercialActionPerformed(evt);
            }
        });

        fSLabel16.setBorder(null);
        fSLabel16.setText("Ciudad");

        Tfciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfciudadActionPerformed(evt);
            }
        });

        fSLabel17.setBorder(null);
        fSLabel17.setText("Barrio");

        Tfbarrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfbarrioActionPerformed(evt);
            }
        });

        fSLabel18.setBorder(null);
        fSLabel18.setText("Calle");

        Tfcalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfcalleActionPerformed(evt);
            }
        });

        fSLabel19.setBorder(null);
        fSLabel19.setText("Capacidad de endeudamiento");

        Tfcapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfcapacidadActionPerformed(evt);
            }
        });

        fSLabel20.setBorder(null);
        fSLabel20.setText("Linea principal");

        Tflinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TflineaActionPerformed(evt);
            }
        });

        fSLabel21.setBorder(null);
        fSLabel21.setText("Marca principal");

        Tfmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfmarcaActionPerformed(evt);
            }
        });

        fSLabel22.setBorder(null);
        fSLabel22.setText("Cantidad de sucursales");

        Tfsucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfsucursalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRound1Layout = new javax.swing.GroupLayout(jPanelRound1);
        jPanelRound1.setLayout(jPanelRound1Layout);
        jPanelRound1Layout.setHorizontalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                        .addComponent(fSLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tfsucursales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                        .addComponent(fSLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tfmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                        .addComponent(fSLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tflinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                        .addComponent(fSLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tfcapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                        .addComponent(fSLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tfcalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                        .addComponent(fSLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tfbarrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelRound1Layout.createSequentialGroup()
                            .addComponent(fSLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Tf_nombre_comercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRound1Layout.createSequentialGroup()
                                .addComponent(fSLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Tf_canal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRound1Layout.createSequentialGroup()
                                .addComponent(fSLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Tfdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRound1Layout.createSequentialGroup()
                                .addComponent(fSLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Tfpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRound1Layout.createSequentialGroup()
                                .addComponent(fSLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Tfcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRound1Layout.createSequentialGroup()
                                .addComponent(fSLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Tfindicativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRound1Layout.createSequentialGroup()
                                .addComponent(fSLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Tfproveedor_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRound1Layout.createSequentialGroup()
                                .addComponent(fSLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Tf_intro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelRound1Layout.createSequentialGroup()
                                    .addComponent(fSLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Tf_actividad_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelRound1Layout.createSequentialGroup()
                                    .addComponent(fSLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Tf_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelRound1Layout.createSequentialGroup()
                                    .addComponent(fSLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Tfcorreo_secundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                                        .addComponent(fSLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Tfcorreo_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                                        .addComponent(fSLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Tf_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                                        .addComponent(fSLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Tf_web, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelRound1Layout.createSequentialGroup()
                                .addComponent(fSLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Tfciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanelRound1Layout.setVerticalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_nombre_comercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_canal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_web, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tfcorreo_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tfcorreo_secundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_actividad_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_intro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tfproveedor_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tfindicativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tfcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tfpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tfdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tfciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tfbarrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tfcalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tfcapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tflinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tfmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tfsucursales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanelRound1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(fSButtonMD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fSButtonMD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tf_webActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_webActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_webActionPerformed

    private void Tf_tiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_tiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_tiempoActionPerformed

    private void Tfcorreo_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tfcorreo_principalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tfcorreo_principalActionPerformed

    private void Tfcorreo_secundarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tfcorreo_secundarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tfcorreo_secundarioActionPerformed

    private void Tf_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_tipoActionPerformed

    private void Tf_actividad_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_actividad_principalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_actividad_principalActionPerformed

    private void Tf_introActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_introActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_introActionPerformed

    private void Tfproveedor_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tfproveedor_principalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tfproveedor_principalActionPerformed

    private void TfindicativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfindicativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfindicativoActionPerformed

    private void TfcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfcelActionPerformed

    private void TfpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfpaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfpaisActionPerformed

    private void TfdepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfdepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfdepartamentoActionPerformed

    private void Tf_canalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_canalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_canalActionPerformed

    private void Tf_nombre_comercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_nombre_comercialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_nombre_comercialActionPerformed

    private void TfciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfciudadActionPerformed

    private void TfbarrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfbarrioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfbarrioActionPerformed

    private void TfcalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfcalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfcalleActionPerformed

    private void TfcapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfcapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfcapacidadActionPerformed

    private void TflineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TflineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TflineaActionPerformed

    private void TfmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfmarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfmarcaActionPerformed

    private void TfsucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfsucursalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfsucursalesActionPerformed

    private void fSButtonMD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSButtonMD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fSButtonMD1ActionPerformed

    private void fSButtonMD1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fSButtonMD1MouseClicked
        // TODO add your handling code here:
        PreparedStatement insert;
   
        try {
            String sql = "CALL INSERTAR_CLIENTE (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            
            PreparedStatement sentencia= cnx.prepareStatement(sql);
            sentencia.setString(1, Tf_nombre_comercial.getText());
            sentencia.setString(2, Tf_canal.getText());
            sentencia.setString(3, Tf_web.getText());
            sentencia.setString(4, Tf_tiempo.getText());
            sentencia.setString(5, Tfcorreo_principal.getText());
            sentencia.setString(6, Tfcorreo_secundario.getText());
            sentencia.setString(7, Tf_tipo.getText());
            sentencia.setString(8, Tf_actividad_principal.getText());
            sentencia.setString(9, Tf_intro.getText());
            sentencia.setString(10, Tfproveedor_principal.getText());
            sentencia.setInt(11, Integer.parseInt (Tfindicativo.getText()));
            sentencia.setString(12, Tfcel.getText());
            sentencia.setString(13, Tfpais.getText());
            sentencia.setString(14, Tfdepartamento.getText());
            sentencia.setString(15, Tfciudad.getText());
            sentencia.setString(16, Tfbarrio.getText());
            sentencia.setString(17, Tfcalle.getText());
            sentencia.setInt(18, Integer.parseInt (Tfcapacidad.getText()));
            sentencia.setString(19,Tflinea.getText());
            sentencia.setString(20,Tfmarca.getText());
            sentencia.setInt(21,Integer.parseInt (Tfsucursales.getText()));
            
            sentencia.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Cliente"+Tf_nombre_comercial.getText()+" creado con exito.");
            Admin_page ap= new Admin_page(cnx);
            DefaultTableModel model =(DefaultTableModel) t_clientes.getModel();
            model.setRowCount(0);
            ap.llenar_tabla(22,t_clientes,"CALL SHOW_CLIENTE()");
            
        } catch (SQLException ex) {
            Logger.getLogger(Cl_form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fSButtonMD1MouseClicked

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSTexFieldMD Tf_actividad_principal;
    private LIB.FSTexFieldMD Tf_canal;
    private LIB.FSTexFieldMD Tf_intro;
    private LIB.FSTexFieldMD Tf_nombre_comercial;
    private LIB.FSTexFieldMD Tf_tiempo;
    private LIB.FSTexFieldMD Tf_tipo;
    private LIB.FSTexFieldMD Tf_web;
    private LIB.FSTexFieldMD Tfbarrio;
    private LIB.FSTexFieldMD Tfcalle;
    private LIB.FSTexFieldMD Tfcapacidad;
    private LIB.FSTexFieldMD Tfcel;
    private LIB.FSTexFieldMD Tfciudad;
    private LIB.FSTexFieldMD Tfcorreo_principal;
    private LIB.FSTexFieldMD Tfcorreo_secundario;
    private LIB.FSTexFieldMD Tfdepartamento;
    private LIB.FSTexFieldMD Tfindicativo;
    private LIB.FSTexFieldMD Tflinea;
    private LIB.FSTexFieldMD Tfmarca;
    private LIB.FSTexFieldMD Tfpais;
    private LIB.FSTexFieldMD Tfproveedor_principal;
    private LIB.FSTexFieldMD Tfsucursales;
    private LIB.FSButtonMD fSButtonMD1;
    private LIB.FSLabel fSLabel10;
    private LIB.FSLabel fSLabel11;
    private LIB.FSLabel fSLabel12;
    private LIB.FSLabel fSLabel13;
    private LIB.FSLabel fSLabel14;
    private LIB.FSLabel fSLabel15;
    private LIB.FSLabel fSLabel16;
    private LIB.FSLabel fSLabel17;
    private LIB.FSLabel fSLabel18;
    private LIB.FSLabel fSLabel19;
    private LIB.FSLabel fSLabel2;
    private LIB.FSLabel fSLabel20;
    private LIB.FSLabel fSLabel21;
    private LIB.FSLabel fSLabel22;
    private LIB.FSLabel fSLabel3;
    private LIB.FSLabel fSLabel4;
    private LIB.FSLabel fSLabel5;
    private LIB.FSLabel fSLabel6;
    private LIB.FSLabel fSLabel7;
    private LIB.FSLabel fSLabel8;
    private LIB.FSLabel fSLabel9;
    private LIB.FSTexFieldMD fSTexFieldMD1;
    private LIB.JPanelRound jPanelRound1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
