/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import control.*;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.AdjustmentListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.math.BigDecimal;
import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class InterfazCliente extends javax.swing.JFrame {

    /**
     * Creates new form InterfazCliente
     */
    public InterfazCliente() {
        setPreferredSize(new Dimension(980, 510));
        initComponents();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
		cerrar();
            }
	});
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);
        jPanel1.setPreferredSize(new Dimension(974, 820));
        jScrollPane2.setViewportView(jPanel1);

        this.mostrarHistorial();
        this.mostrarEstadisticas();
        
        ImageIcon imagen1 = new ImageIcon(getClass().getResource("/Imagenes/imagenMotCliente.png"));
        Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(labelImagen.getWidth(), labelImagen.getHeight(), Image.SCALE_SMOOTH));
        labelImagen.setIcon(fondo1);      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane2.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textHistCompras = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textProductoMas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textPromCompras = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textMarcaMas = new javax.swing.JTextField();
        labelImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(974, 510));

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Producto que mas compras / Unidades");

        btnCerrarSesion.setBackground(new java.awt.Color(73, 181, 172));
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.setRequestFocusEnabled(false);
        btnCerrarSesion.setRolloverEnabled(false);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(73, 181, 172));
        jLabel1.setText("Bienvenido de Nuevo!");

        textHistCompras.setBackground(new java.awt.Color(238, 232, 224));
        textHistCompras.setColumns(20);
        textHistCompras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textHistCompras.setRows(5);
        textHistCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textHistCompras.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        textHistCompras.setEnabled(false);
        jScrollPane1.setViewportView(textHistCompras);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Historial de Compras");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(73, 181, 172));
        jLabel5.setText("Tus Estadísticas");

        textProductoMas.setEditable(false);
        textProductoMas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textProductoMas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Marca que mas compras / Unidades");

        textPromCompras.setEditable(false);
        textPromCompras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPromCompras.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(73, 181, 172));
        jLabel8.setText("PROMEDIO DE COMPRAS");

        textMarcaMas.setEditable(false);
        textMarcaMas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textMarcaMas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesion)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textProductoMas)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textMarcaMas)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textPromCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(0, 37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(355, 355, 355))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(348, 348, 348))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textProductoMas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMarcaMas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(textPromCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        try{
            control.Main.getCrearConexion().getConexion().close();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Hasta pronto!");
            System.exit(0);
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Error, no se ha podido cerrar su sesion.\nPor favor vuelva a intentarlo",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCerrarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JTextArea textHistCompras;
    private javax.swing.JTextField textMarcaMas;
    private javax.swing.JTextField textProductoMas;
    private javax.swing.JTextField textPromCompras;
    // End of variables declaration//GEN-END:variables
    private void cerrar(){
        getToolkit().beep();
        String botones[] = {"Salir", "Cancelar"};
	int election = JOptionPane.showOptionDialog(null, "Desea cerrar la aplicacion?\n"
                + "(Su sesion se va a cerrar)", "Confirmar", 0, 0, null, botones, this);
	if (election == JOptionPane.YES_OPTION) {
            try{
                control.Main.getCrearConexion().getConexion().close();
                System.exit(0);
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Error, no se ha podido cerrar su sesion.\nPor favor vuelva a intentarlo", 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
            
	}
    }
    
    private void mostrarHistorial(){
        try{
            Statement s = control.Main.getCrearConexion().getConexion().createStatement();
            ResultSet rs = s.executeQuery ("SELECT getIDClienteSesion()");
            int id = 0;
            while(rs.next()){
                id = rs.getInt(1);
            }

            String consultaSQL1 = "CALL CLIENTE_HISTORIAL(?)";
            PreparedStatement stmt = control.Main.getCrearConexion().getConexion().prepareCall(consultaSQL1);
            stmt.setInt(1, id);
            rs = stmt.executeQuery();
            
            String historial = "";
            while(rs.next()){
                historial +=  
                        "Nombre de la categoria: " + rs.getString(1)+"\n"
                        +"Prod. Cod: " + rs.getInt(2)+"\n"
                        +"ID Detalle Factura: " + rs.getInt(3)+"\n"
                        +"ID Factura: " + rs.getInt(4)+"\n"
                        +"ID Compra: " + rs.getInt(5)+"\n"
                        +"Unidades: " + rs.getInt(29)+"\n"
                        +"Total:$ " + rs.getInt(30)+"\n"
                        +"IVA:$ " + rs.getInt(31)+"\n"
                        +"Fecha: " + rs.getString(32)+"\n"
                        +"Codigo de Vendedor: " + rs.getInt(33)+"\n"
                        +"Cantidad detalle factura: " + rs.getInt(34)+"\n"
                        +"Subtotal detalle factura:$ " + rs.getInt(35)+"\n"
                        +"Nombre Producto: " + rs.getString(38)+"\n"
                        +"Marca: " + rs.getString(39)+"\n"
                        +"\n"+"\n"+"-----------------------------------------------------------------------------"
                        +"\n"+"\n";
            }
            
            textHistCompras.setText(historial);
            
        }catch(SQLException e){
            System.out.println(e);
        }
        
    }
    
    private void mostrarEstadisticas(){
        try{
            Statement s = control.Main.getCrearConexion().getConexion().createStatement();
            ResultSet rs = s.executeQuery ("SELECT getIDClienteSesion()");
            int id = 0;
            while(rs.next()){
                id = rs.getInt(1);
            }
            
            String consultaSQL1 = "CALL CLIENTE_PRODUCTO_MAS_COMPRADO(?)";
            PreparedStatement stmt = control.Main.getCrearConexion().getConexion().prepareCall(consultaSQL1);
            stmt.setInt(1, id);
            rs = stmt.executeQuery();
            
            String prodctoMasComprado = "";
            
            while(rs.next()){
                prodctoMasComprado += rs.getString(1)
                        + "\t" + "/" +"\t"
                        + rs.getInt(2);
            }
            
            textProductoMas.setText(prodctoMasComprado);
            
            consultaSQL1 = "CALL CLIENTE_MARCA_MAS_COMPRADA(?)";
            stmt = control.Main.getCrearConexion().getConexion().prepareCall(consultaSQL1);
            stmt.setInt(1, id);
            rs = stmt.executeQuery();
            
            String marcaMasComprada = "";
            
            while(rs.next()){
                marcaMasComprada += rs.getString(1)
                        + "\t" + "/" +"\t"
                        + rs.getInt(2);
            }
            
            textMarcaMas.setText(marcaMasComprada);
            
            consultaSQL1 = "CALL CLIENTE_PROMEDIO_COMPRA(?)";
            stmt = control.Main.getCrearConexion().getConexion().prepareCall(consultaSQL1);
            stmt.setInt(1, id);
            rs = stmt.executeQuery();
            
            String promedioCompra = "";
            
            while(rs.next()){
                promedioCompra += "$ " + rs.getString(2);
            }
            
            textPromCompras.setText(promedioCompra);
            
        }catch (SQLException e){
            System.out.println(e);
        }
        
    }
}
