/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.Date;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class InterfazAgente extends javax.swing.JFrame {
    
    Admin_page admin;

    /**
     * Creates new form InterfazAgente
     */
    public InterfazAgente() {
        initComponents();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
		cerrar();
            }
	});
        llenar_tabla(8,jTproductos1,"CALL SHOW_PRODUCTO()");
        llenar_tabla(22,jTClientes1,"CALL SHOW_CLIENTE()");
        llenar_tabla(15,jTclientes_consolidados,"CALL SHOW_CLIENTE_CONSOLIDADO()");
        llenar_tabla(9,jTempresas,"CALL SHOW_EMPRESA()");
        llenar_tabla(17,jT_facturas,"CALL SHOW_FACTURA()");
        
        ImageIcon imagen1 = new ImageIcon(getClass().getResource("/Imagenes/buscar.png"));
        Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(labelBuscar.getWidth(), labelBuscar.getHeight(), Image.SCALE_SMOOTH));
        labelBuscar.setIcon(fondo1);
        
        selecFechaLlamada.setMaxSelectableDate(new Date());
        
        //ImageIcon imagen2 = new ImageIcon(getClass().getResource("/Imagenes/Fondo Boton.png"));
        //Icon fondo2 = new ImageIcon(imagen2.getImage().getScaledInstance(btnAgregarRespuesta.getWidth(), btnAgregarRespuesta.getHeight(), Image.SCALE_SMOOTH));
        //btnAgregarRespuesta.setIcon(fondo2);

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        jScrollPane3.getVerticalScrollBar().setUnitIncrement(16);
        
        this.saludo();
        this.insertMetasTable(tablaMetas);
        this.insertHistorialTable(tablaHistorial);
        this.colocarEstadisticas();
        this.createTablaProductos(tablaProductos);
        this.consultarPreguntas(tablaPreguntas);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelSaludo = new javax.swing.JLabel();
        jPanelRound2 = new LIB.JPanelRound();
        jLabel3 = new javax.swing.JLabel();
        fSGradientPanel2 = new LIB.FSGradientPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMetas = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textVentasTotales = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textTasaVenta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textPromedioVentas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        labelSaludo1 = new javax.swing.JLabel();
        textBuscarCliente = new javax.swing.JTextField();
        labelBuscar = new javax.swing.JLabel();
        labelRespuestaBusqueda = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaResultadoCliente = new javax.swing.JTable();
        jScrollPane15 = new javax.swing.JScrollPane();
        jp_pagina_clientes = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTClientes1 = new javax.swing.JTable();
        lb_pagina_clientes = new java.awt.Label();
        fSButtonMD3 = new LIB.FSButtonMD();
        Jb_Compra = new LIB.FSButtonMD();
        jScrollPane12 = new javax.swing.JScrollPane();
        jT_facturas = new javax.swing.JTable();
        fSLabel2 = new LIB.FSLabel();
        fSLabel3 = new LIB.FSLabel();
        fSButtonMD7 = new LIB.FSButtonMD();
        fSLabel4 = new LIB.FSLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTempresas = new javax.swing.JTable();
        fSLabel5 = new LIB.FSLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTclientes_consolidados = new javax.swing.JTable();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTproductos1 = new javax.swing.JTable();
        fSLabel7 = new LIB.FSLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        textLlamadaIDCliente = new LIB.FSTexFieldMD();
        llamadaServicio = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        llamadaEstado = new javax.swing.JComboBox<>();
        textLlamadaSatisfC = new LIB.FSTexFieldMD();
        jLabel11 = new javax.swing.JLabel();
        llamadaResolucion = new javax.swing.JComboBox<>();
        textPreguntaCanal = new LIB.FSTexFieldMD();
        jScrollPane8 = new javax.swing.JScrollPane();
        textDetalle = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jPanelRound1 = new LIB.JPanelRound();
        jPanelRound4 = new LIB.JPanelRound();
        labelAgregarPregunta = new javax.swing.JLabel();
        fSGradientPanel3 = new LIB.FSGradientPanel();
        selecFechaLlamada = new com.toedter.calendar.JDateChooser();
        textLlamadaHora = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        textLlamadaTiempoE = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        textLlamadaTiempoConv = new javax.swing.JFormattedTextField();
        jScrollPane16 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        textCodCliente = new javax.swing.JTextField();
        jPanelRound3 = new LIB.JPanelRound();
        labelBuscarPreguntasCl = new javax.swing.JLabel();
        fSGradientPanel1 = new LIB.FSGradientPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        tablaPreguntas = new javax.swing.JTable();
        btnAgregarRespuesta = new javax.swing.JButton();
        btnVerRegistroCompleto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));

        labelSaludo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelSaludo.setForeground(new java.awt.Color(73, 181, 172));
        labelSaludo.setText("Bienvenid@ de nuevo, ");

        jPanelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cerrar Sesión");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanelRound2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 50));

        fSGradientPanel2.setFSEndColor(new java.awt.Color(73, 181, 172));
        fSGradientPanel2.setFSStartColor(new java.awt.Color(73, 181, 172));

        javax.swing.GroupLayout fSGradientPanel2Layout = new javax.swing.GroupLayout(fSGradientPanel2);
        fSGradientPanel2.setLayout(fSGradientPanel2Layout);
        fSGradientPanel2Layout.setHorizontalGroup(
            fSGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        fSGradientPanel2Layout.setVerticalGroup(
            fSGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanelRound2.add(fSGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labelSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 672, Short.MAX_VALUE)
                .addComponent(jPanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(100, 700));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(33, 45, 62));

        tablaMetas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tablaMetas.setForeground(new java.awt.Color(73, 181, 172));
        tablaMetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaMetas.setGridColor(new java.awt.Color(73, 181, 172));
        jScrollPane2.setViewportView(tablaMetas);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(73, 181, 172));
        jLabel15.setText("Tus Metas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1755, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jTabbedPane1.addTab("Mis Metas", jScrollPane1);

        jPanel3.setBackground(new java.awt.Color(33, 45, 62));
        jPanel3.setPreferredSize(new java.awt.Dimension(873, 1938));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(73, 181, 172));
        jLabel1.setText("Tu Historial");

        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaHistorial);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(73, 181, 172));
        jLabel2.setText("Tus Estadísticas");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Monto Total en Ventas");

        textVentasTotales.setEditable(false);
        textVentasTotales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textVentasTotales.setForeground(new java.awt.Color(73, 181, 172));
        textVentasTotales.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textVentasTotales.setCaretColor(new java.awt.Color(73, 181, 172));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tasa de venta (por monto vendido)");

        textTasaVenta.setEditable(false);
        textTasaVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textTasaVenta.setForeground(new java.awt.Color(73, 181, 172));
        textTasaVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textTasaVenta.setCaretColor(new java.awt.Color(73, 181, 172));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Promedio de Ventas");

        textPromedioVentas.setEditable(false);
        textPromedioVentas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPromedioVentas.setForeground(new java.awt.Color(73, 181, 172));
        textPromedioVentas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textPromedioVentas.setCaretColor(new java.awt.Color(73, 181, 172));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(73, 181, 172));
        jLabel7.setText("\"Llegar juntos es el principio. Mantenerse juntos, es el progreso. Trabajar juntos es el éxito\". Henry Ford.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textVentasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textTasaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPromedioVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel7)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textVentasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTasaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPromedioVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(jLabel7)
                .addContainerGap(1703, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel3);

        jTabbedPane1.addTab("Mi Historial y Estadísticas", jScrollPane3);

        jPanel4.setBackground(new java.awt.Color(33, 45, 62));

        labelSaludo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelSaludo1.setForeground(new java.awt.Color(73, 181, 172));
        labelSaludo1.setText("Ingresa el nombre comercial del Cliente a buscar:");

        textBuscarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBuscarMouseClicked(evt);
            }
        });

        labelRespuestaBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelRespuestaBusqueda.setForeground(new java.awt.Color(73, 181, 172));

        tablaResultadoCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tablaResultadoCliente);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSaludo1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelRespuestaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(textBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 1398, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelSaludo1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(labelRespuestaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1791, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(jPanel4);

        jTabbedPane1.addTab("Buscar Cliente", jScrollPane5);

        jp_pagina_clientes.setBackground(new java.awt.Color(33, 45, 62));

        jTClientes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre comercial", "Canal venta", "Website", "tiempo mercado", "Correo principal", "Correo secundario", "Tipo", "Actividad principal", "Intro", "Proveedor principal", "Indicador tel", "telefono", "pais", "departamento", "Ciudad", "Barrio", "Calle", "Capacidad endeudamiento", "Actividad principal", "Marca principal", "Cantidad de sucursales"
            }
        ));
        jScrollPane11.setViewportView(jTClientes1);

        lb_pagina_clientes.setText("Tabla de Clientes");

        fSButtonMD3.setBackground(new java.awt.Color(0, 153, 153));
        fSButtonMD3.setText("Agregar Cliente");
        fSButtonMD3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fSButtonMD3MouseClicked(evt);
            }
        });
        fSButtonMD3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                fSButtonMD3ComponentHidden(evt);
            }
        });
        fSButtonMD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSButtonMD3ActionPerformed(evt);
            }
        });

        Jb_Compra.setText("Agregar compra Cliente");
        Jb_Compra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jb_CompraMouseClicked(evt);
            }
        });
        Jb_Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jb_CompraActionPerformed(evt);
            }
        });

        jT_facturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16", "Title 17"
            }
        ));
        jScrollPane12.setViewportView(jT_facturas);

        fSLabel2.setBackground(new java.awt.Color(0, 204, 204));
        fSLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fSLabel2.setForeground(new java.awt.Color(255, 255, 255));
        fSLabel2.setText("Tabla de facturas");
        fSLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        fSLabel3.setBackground(new java.awt.Color(0, 204, 204));
        fSLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fSLabel3.setForeground(new java.awt.Color(255, 255, 255));
        fSLabel3.setText("Tabla clientess");
        fSLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        fSButtonMD7.setBackground(new java.awt.Color(0, 153, 153));
        fSButtonMD7.setText("Actualizar tablas");
        fSButtonMD7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fSButtonMD7MouseClicked(evt);
            }
        });
        fSButtonMD7.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                fSButtonMD7ComponentHidden(evt);
            }
        });
        fSButtonMD7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSButtonMD7ActionPerformed(evt);
            }
        });

        fSLabel4.setBackground(new java.awt.Color(0, 204, 204));
        fSLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fSLabel4.setForeground(new java.awt.Color(255, 255, 255));
        fSLabel4.setText("Tabla de empresas");
        fSLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTempresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jScrollPane13.setViewportView(jTempresas);

        fSLabel5.setBackground(new java.awt.Color(0, 204, 204));
        fSLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fSLabel5.setForeground(new java.awt.Color(255, 255, 255));
        fSLabel5.setText("Tabla de Clientes consolidados");
        fSLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTclientes_consolidados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15"
            }
        ));
        jScrollPane14.setViewportView(jTclientes_consolidados);

        jTproductos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Categoría", "Nombre", "Marca", "Unidades", "Precio unitario", "Precio secundario", "Especificación"
            }
        ));
        jTproductos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTproductos1MouseClicked(evt);
            }
        });
        jScrollPane18.setViewportView(jTproductos1);

        fSLabel7.setBackground(new java.awt.Color(0, 204, 204));
        fSLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fSLabel7.setForeground(new java.awt.Color(255, 255, 255));
        fSLabel7.setText("Tabla de productos");
        fSLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jp_pagina_clientesLayout = new javax.swing.GroupLayout(jp_pagina_clientes);
        jp_pagina_clientes.setLayout(jp_pagina_clientesLayout);
        jp_pagina_clientesLayout.setHorizontalGroup(
            jp_pagina_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_pagina_clientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_pagina_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(572, 572, 572))
            .addGroup(jp_pagina_clientesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jp_pagina_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11)
                    .addGroup(jp_pagina_clientesLayout.createSequentialGroup()
                        .addGroup(jp_pagina_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_pagina_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_pagina_clientesLayout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addGroup(jp_pagina_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fSLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fSLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 1071, Short.MAX_VALUE)
                                        .addComponent(jScrollPane18))))
                            .addGroup(jp_pagina_clientesLayout.createSequentialGroup()
                                .addComponent(fSButtonMD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(fSButtonMD7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(Jb_Compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_pagina_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fSLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
                                .addComponent(fSLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 392, Short.MAX_VALUE))
                    .addComponent(fSLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jp_pagina_clientesLayout.setVerticalGroup(
            jp_pagina_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_pagina_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_pagina_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(fSLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_pagina_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSButtonMD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jb_Compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fSButtonMD7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(fSLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(fSLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fSLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fSLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        jScrollPane15.setViewportView(jp_pagina_clientes);

        jTabbedPane1.addTab("Clientes y compras", jScrollPane15);

        jPanel6.setBackground(new java.awt.Color(33, 45, 62));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(tablaProductos);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(73, 181, 172));
        jLabel16.setText("Estos son los productos actuales en inventario");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1752, Short.MAX_VALUE))
        );

        jScrollPane9.setViewportView(jPanel6);

        jTabbedPane1.addTab("Ver Productos", jScrollPane9);

        jPanel5.setBackground(new java.awt.Color(33, 45, 62));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(73, 181, 172));
        jLabel8.setText("Registro de la Llamada");

        textLlamadaIDCliente.setForeground(new java.awt.Color(73, 181, 172));
        textLlamadaIDCliente.setBordeColorFocus(new java.awt.Color(73, 181, 172));
        textLlamadaIDCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textLlamadaIDCliente.setPlaceholder("ID Cliente");
        textLlamadaIDCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textLlamadaIDClienteKeyTyped(evt);
            }
        });

        llamadaServicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        llamadaServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VENTA", "ATENCION AL CLIENTE" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Resolución");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Estado");

        llamadaEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        llamadaEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CONTESTADA", "NO CONTESTADA" }));
        llamadaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llamadaEstadoActionPerformed(evt);
            }
        });

        textLlamadaSatisfC.setForeground(new java.awt.Color(73, 181, 172));
        textLlamadaSatisfC.setBordeColorFocus(new java.awt.Color(73, 181, 172));
        textLlamadaSatisfC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textLlamadaSatisfC.setPlaceholder("Satisfacción Cliente");
        textLlamadaSatisfC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textLlamadaSatisfCKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Servicio");

        llamadaResolucion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        llamadaResolucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LLAMADA ABANDONADA", "VENTA CONCRETADA", "VENTA NO CONCRETADA", "SERVICIO ATENDIDO", "SERVICIO NO ATENDIDO" }));

        textPreguntaCanal.setForeground(new java.awt.Color(73, 181, 172));
        textPreguntaCanal.setBordeColorFocus(new java.awt.Color(73, 181, 172));
        textPreguntaCanal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textPreguntaCanal.setPlaceholder("Canal");

        textDetalle.setColumns(20);
        textDetalle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textDetalle.setRows(5);
        jScrollPane8.setViewportView(textDetalle);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Detalle");

        jPanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAgregarPregunta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelAgregarPregunta.setForeground(new java.awt.Color(255, 255, 255));
        labelAgregarPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAgregarPregunta.setText("Agregar Pregunta");
        labelAgregarPregunta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelAgregarPregunta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAgregarPreguntaMouseClicked(evt);
            }
        });
        jPanelRound4.add(labelAgregarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        fSGradientPanel3.setFSEndColor(new java.awt.Color(73, 181, 172));
        fSGradientPanel3.setFSStartColor(new java.awt.Color(73, 181, 172));

        javax.swing.GroupLayout fSGradientPanel3Layout = new javax.swing.GroupLayout(fSGradientPanel3);
        fSGradientPanel3.setLayout(fSGradientPanel3Layout);
        fSGradientPanel3Layout.setHorizontalGroup(
            fSGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        fSGradientPanel3Layout.setVerticalGroup(
            fSGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelRound4.add(fSGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        selecFechaLlamada.setForeground(new java.awt.Color(73, 181, 172));
        selecFechaLlamada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        textLlamadaHora.setForeground(new java.awt.Color(73, 181, 172));
        try {
            textLlamadaHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textLlamadaHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Fecha");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Hora");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Tiempo de Espera");

        textLlamadaTiempoE.setForeground(new java.awt.Color(73, 181, 172));
        try {
            textLlamadaTiempoE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textLlamadaTiempoE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Tiempo de Conversación");

        textLlamadaTiempoConv.setForeground(new java.awt.Color(73, 181, 172));
        try {
            textLlamadaTiempoConv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textLlamadaTiempoConv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 1445, Short.MAX_VALUE)
                            .addComponent(jPanelRound4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textLlamadaIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textLlamadaSatisfC, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selecFechaLlamada, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textLlamadaHora)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(textLlamadaTiempoE, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(llamadaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(llamadaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textLlamadaTiempoConv, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(llamadaResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(textPreguntaCanal, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selecFechaLlamada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(llamadaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textLlamadaIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(llamadaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textLlamadaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textLlamadaTiempoE, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textLlamadaTiempoConv, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLlamadaSatisfC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(llamadaResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPreguntaCanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jPanelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1876, Short.MAX_VALUE))
        );

        jScrollPane7.setViewportView(jPanel5);

        jTabbedPane1.addTab("Agregar Llamada/Pregunta", jScrollPane7);

        jPanel7.setBackground(new java.awt.Color(33, 45, 62));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(73, 181, 172));
        jLabel12.setText("Registros de Preguntas con los Clientes");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ingresa el ID del cliente");

        textCodCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCodClienteKeyTyped(evt);
            }
        });

        jPanelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelBuscarPreguntasCl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelBuscarPreguntasCl.setForeground(new java.awt.Color(255, 255, 255));
        labelBuscarPreguntasCl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBuscarPreguntasCl.setText("Buscar Preguntas");
        labelBuscarPreguntasCl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBuscarPreguntasCl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBuscarPreguntasClMouseClicked(evt);
            }
        });
        jPanelRound3.add(labelBuscarPreguntasCl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        fSGradientPanel1.setFSEndColor(new java.awt.Color(73, 181, 172));
        fSGradientPanel1.setFSStartColor(new java.awt.Color(73, 181, 172));

        javax.swing.GroupLayout fSGradientPanel1Layout = new javax.swing.GroupLayout(fSGradientPanel1);
        fSGradientPanel1.setLayout(fSGradientPanel1Layout);
        fSGradientPanel1Layout.setHorizontalGroup(
            fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        fSGradientPanel1Layout.setVerticalGroup(
            fSGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelRound3.add(fSGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tablaPreguntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane17.setViewportView(tablaPreguntas);

        btnAgregarRespuesta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarRespuesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Boton.png"))); // NOI18N
        btnAgregarRespuesta.setText("Agregar Respuesta");
        btnAgregarRespuesta.setBorderPainted(false);
        btnAgregarRespuesta.setContentAreaFilled(false);
        btnAgregarRespuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarRespuesta.setFocusPainted(false);
        btnAgregarRespuesta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarRespuesta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Boton.png"))); // NOI18N
        btnAgregarRespuesta.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Boton.png"))); // NOI18N
        btnAgregarRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRespuestaActionPerformed(evt);
            }
        });

        btnVerRegistroCompleto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVerRegistroCompleto.setForeground(new java.awt.Color(255, 255, 255));
        btnVerRegistroCompleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Boton.png"))); // NOI18N
        btnVerRegistroCompleto.setText("Ver Registro");
        btnVerRegistroCompleto.setBorderPainted(false);
        btnVerRegistroCompleto.setContentAreaFilled(false);
        btnVerRegistroCompleto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerRegistroCompleto.setFocusPainted(false);
        btnVerRegistroCompleto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerRegistroCompleto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Boton.png"))); // NOI18N
        btnVerRegistroCompleto.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Boton.png"))); // NOI18N
        btnVerRegistroCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRegistroCompletoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(textCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(jPanelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100)
                                .addComponent(btnAgregarRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(btnVerRegistroCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerRegistroCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1756, Short.MAX_VALUE))
        );

        jScrollPane16.setViewportView(jPanel7);

        jTabbedPane1.addTab("Ver Llamadas/Preguntas y Agregar Respuestas", jScrollPane16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2423, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try{
            control.Main.getCrearConexion().getConexion().close();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Hasta pronto!");
            System.exit(0);
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Error, no se ha podido cerrar su sesion.\nPor favor vuelva a intentarlo",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        this.insertMetasTable(tablaMetas);
        this.insertHistorialTable(tablaHistorial);
        this.colocarEstadisticas();
        this.createTablaProductos(tablaProductos);
        this.consultarPreguntas(tablaPreguntas);

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void labelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarMouseClicked
        getToolkit().beep();
        this.createTableBusqueda(tablaResultadoCliente, textBuscarCliente.getText());
    }//GEN-LAST:event_labelBuscarMouseClicked

    private void llamadaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llamadaEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_llamadaEstadoActionPerformed

    private void labelAgregarPreguntaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAgregarPreguntaMouseClicked
        if(!this.verificarHora(textLlamadaHora.getText()) || !this.verificarHora(textLlamadaTiempoE.getText()) ||
                !this.verificarHora(textLlamadaTiempoConv.getText())){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Error.\nLos datos introducidos en la hora no son validos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            Statement s = control.Main.getCrearConexion().getConexion().createStatement();
            ResultSet rs = s.executeQuery ("SELECT getIDAgente()");
            int id = 0;
            while(rs.next()){
                id = rs.getInt(1);
            }
            
            SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
            String dateLlamada = dFormat.format(selecFechaLlamada.getDate());
            dateLlamada += " " + textLlamadaHora.getText();

            CallableStatement stmt = control.Main.getCrearConexion().getConexion().
            prepareCall("{CALL INSERT_Pregunta(?,?,?,?,?,?,?,?,?,?,?,?,?)}");
            stmt.setInt(1, Integer.parseInt(textLlamadaIDCliente.getText()));
            stmt.setInt(2, id);
            stmt.setString(3, dateLlamada);
            stmt.setString(4, textLlamadaTiempoE.getText());
            stmt.setString(5, llamadaServicio.getSelectedItem().toString());
            stmt.setString(6, llamadaEstado.getSelectedItem().toString());
            stmt.setString(7, textLlamadaTiempoConv.getText());
            stmt.setString(8, textLlamadaSatisfC.getText());
            stmt.setString(9, llamadaResolucion.getSelectedItem().toString());
            stmt.setString(10, textDetalle.getText());
            stmt.setString(11, textPreguntaCanal.getText());
            stmt.setString(12, llamadaEstado.getSelectedItem().toString());
            stmt.setString(13, dateLlamada);

            stmt.execute();

            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Pregunta Agregada Correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            textLlamadaHora.setText("");
            textLlamadaIDCliente.setText("");
            textLlamadaTiempoE.setText("");
            textLlamadaTiempoConv.setText("");
            textLlamadaSatisfC.setText("");
            textDetalle.setText("");
            textPreguntaCanal.setText("");
        }catch(Exception e){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Se ha producido un error.\nRevisa los datos e intentalo de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }

    }//GEN-LAST:event_labelAgregarPreguntaMouseClicked

    private void labelBuscarPreguntasClMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarPreguntasClMouseClicked
        this.consultarPreguntas(tablaPreguntas);
    }//GEN-LAST:event_labelBuscarPreguntasClMouseClicked

    private void btnAgregarRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRespuestaActionPerformed
        this.agregarRespuesta();
    }//GEN-LAST:event_btnAgregarRespuestaActionPerformed

    private void textLlamadaIDClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textLlamadaIDClienteKeyTyped
        char valdiar = evt.getKeyChar();
        
        if(Character.isLetter(valdiar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textLlamadaIDClienteKeyTyped

    private void textLlamadaSatisfCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textLlamadaSatisfCKeyTyped
        char valdiar = evt.getKeyChar();
        
        if(Character.isLetter(valdiar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textLlamadaSatisfCKeyTyped

    private void textCodClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCodClienteKeyTyped
        char valdiar = evt.getKeyChar();
        
        if(Character.isLetter(valdiar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textCodClienteKeyTyped

    private void btnVerRegistroCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRegistroCompletoActionPerformed
        this.verRegistroCompleto();
    }//GEN-LAST:event_btnVerRegistroCompletoActionPerformed

    private void fSButtonMD3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fSButtonMD3MouseClicked
        // TODO add your handling code here:
        Cl_form cl = new Cl_form(control.Main.getCrearConexion().getConexion(), jTClientes1);
        cl.setVisible(true);
    }//GEN-LAST:event_fSButtonMD3MouseClicked

    private void fSButtonMD3ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_fSButtonMD3ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_fSButtonMD3ComponentHidden

    private void fSButtonMD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSButtonMD3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fSButtonMD3ActionPerformed

    private void Jb_CompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jb_CompraMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        int fila = jTClientes1.getSelectedRow();
        
        if(fila !=-1){
            
            Boolean vr = verificar_cliente_consolidado();

            if(vr){
                Cl_compra_form_1 compra = new Cl_compra_form_1(control.Main.getCrearConexion().getConexion(), jTClientes1, fila);
                compra.setVisible(true);
            }else{
                Cl_compra_form compra = new Cl_compra_form(control.Main.getCrearConexion().getConexion(), jTClientes1, fila);
                compra.setVisible(true);
            }
              
            
        }else{
            
            JOptionPane.showMessageDialog(null,"Por favor seleccione un cliente");
        }
       

    }//GEN-LAST:event_Jb_CompraMouseClicked

    private void Jb_CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jb_CompraActionPerformed

    }//GEN-LAST:event_Jb_CompraActionPerformed

    private void jTproductos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTproductos1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTproductos1MouseClicked

    private void fSButtonMD7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSButtonMD7ActionPerformed
        // TODO add your handling code here:
        jTClientes1.setModel(new DefaultTableModel());

        jTClientes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre comercial", "Canal venta", "Website", "tiempo mercado", "Correo principal", "Correo secundario", "Tipo", "Actividad principal", "Intro", "Proveedor principal", "Indicador tel", "telefono", "pais", "departamento", "Ciudad", "Barrio", "Calle", "Capacidad endeudamiento", "Actividad principal", "Marca principal", "Cantidad de sucursales"
            }
        ));

        llenar_tabla(22,jTClientes1,"Select * from cliente");
    }//GEN-LAST:event_fSButtonMD7ActionPerformed

    private void fSButtonMD7ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_fSButtonMD7ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_fSButtonMD7ComponentHidden

    private void fSButtonMD7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fSButtonMD7MouseClicked
        // TODO add your handling code here:
            DefaultTableModel model =(DefaultTableModel) jTClientes1.getModel();
            model.setRowCount(0);
            llenar_tabla(22,jTClientes1,"CALL SHOW_CLIENTE()");
            
            DefaultTableModel model2 =(DefaultTableModel) jT_facturas.getModel();
            model2.setRowCount(0);
            llenar_tabla(17,jT_facturas,"CALL SHOW_FACTURA()");

            DefaultTableModel model3 =(DefaultTableModel) jTclientes_consolidados.getModel();
            model3.setRowCount(0);
            llenar_tabla(15,jTclientes_consolidados,"CALL SHOW_CLIENTE_CONSOLIDADO()"); 
    }//GEN-LAST:event_fSButtonMD7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAgente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAgente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAgente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAgente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAgente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD Jb_Compra;
    private javax.swing.JButton btnAgregarRespuesta;
    private javax.swing.JButton btnVerRegistroCompleto;
    private LIB.FSButtonMD fSButtonMD3;
    private LIB.FSButtonMD fSButtonMD7;
    private LIB.FSGradientPanel fSGradientPanel1;
    private LIB.FSGradientPanel fSGradientPanel2;
    private LIB.FSGradientPanel fSGradientPanel3;
    private LIB.FSLabel fSLabel2;
    private LIB.FSLabel fSLabel3;
    private LIB.FSLabel fSLabel4;
    private LIB.FSLabel fSLabel5;
    private LIB.FSLabel fSLabel7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private LIB.JPanelRound jPanelRound1;
    private LIB.JPanelRound jPanelRound2;
    private LIB.JPanelRound jPanelRound3;
    private LIB.JPanelRound jPanelRound4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTClientes1;
    private javax.swing.JTable jT_facturas;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTclientes_consolidados;
    private javax.swing.JTable jTempresas;
    private javax.swing.JTable jTproductos1;
    private javax.swing.JPanel jp_pagina_clientes;
    private javax.swing.JLabel labelAgregarPregunta;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelBuscarPreguntasCl;
    private javax.swing.JLabel labelRespuestaBusqueda;
    private javax.swing.JLabel labelSaludo;
    private javax.swing.JLabel labelSaludo1;
    private java.awt.Label lb_pagina_clientes;
    private javax.swing.JComboBox<String> llamadaEstado;
    private javax.swing.JComboBox<String> llamadaResolucion;
    private javax.swing.JComboBox<String> llamadaServicio;
    private com.toedter.calendar.JDateChooser selecFechaLlamada;
    private javax.swing.JTable tablaHistorial;
    private javax.swing.JTable tablaMetas;
    private javax.swing.JTable tablaPreguntas;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTable tablaResultadoCliente;
    private javax.swing.JTextField textBuscarCliente;
    private javax.swing.JTextField textCodCliente;
    private javax.swing.JTextArea textDetalle;
    private javax.swing.JFormattedTextField textLlamadaHora;
    private LIB.FSTexFieldMD textLlamadaIDCliente;
    private LIB.FSTexFieldMD textLlamadaSatisfC;
    private javax.swing.JFormattedTextField textLlamadaTiempoConv;
    private javax.swing.JFormattedTextField textLlamadaTiempoE;
    private LIB.FSTexFieldMD textPreguntaCanal;
    private javax.swing.JTextField textPromedioVentas;
    private javax.swing.JTextField textTasaVenta;
    private javax.swing.JTextField textVentasTotales;
    // End of variables declaration//GEN-END:variables

    private void cerrar(){
        getToolkit().beep();
        String botones[] = {"Salir", "Cancelar"};
	int election = JOptionPane.showOptionDialog(null, "Desea cerrar la aplicacion?\n"
                + "(Su sesion se va a cerrar)", "Confirmar", 0, 0, null, botones, this);
	if (election == JOptionPane.YES_OPTION) {
            try{
                control.Main.getCrearConexion().getConexion().close();
                System.exit(0);
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Error, no se ha podido cerrar su sesion.\nPor favor vuelva a intentarlo", 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
            
	}
    }
    
Boolean verificar_cliente_consolidado(){
        
        Boolean cliente = false;
        
        int fila = jTClientes1.getSelectedRow();
        
        if(fila!= -1){
          try{                
                CallableStatement pas = control.Main.getCrearConexion().getConexion().prepareCall("{call Cliente_consolidado(?)}");
                pas.setInt(1,(int) jTClientes1.getValueAt(fila, 0));
                ResultSet rs = pas.executeQuery();
                
                while(rs.next()){
                    cliente = true;       
                }
      
            rs.close();
            }catch(Exception e){
            System.out.println("error");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Porfavor seleccione una fila.");
        }
          
        return cliente;
          
        
    }
    
    void llenar_tabla(int columnas, javax.swing.JTable tabla, String sql){
    
        try{
            Statement st= control.Main.getCrearConexion().getConexion().createStatement();
            ResultSet rs=st.executeQuery(sql);
            DefaultTableModel modelo = (DefaultTableModel)tabla.getModel();
            while(rs.next()){
                Object [] fila = new Object[columnas]; 
                for (int i =0;i<columnas;i++){
                    fila[i]= rs.getObject(i+1);     
                }
                modelo.addRow(fila);
            }
            tabla.setModel(modelo);

        }catch(Exception e){
            System.out.println("ERROR AL CARGAR DATOS");
        }
    }
    
        void eliminar_registro() throws SQLException{
        int fila = jTClientes1.getSelectedRow();
        
        String sql2 = "SET FOREIGN_KEY_CHECKS=0;";
        String sql = "DELETE FROM vw_cl WHERE CL_0= ?;";
        PreparedStatement sentencia2= control.Main.getCrearConexion().getConexion().prepareStatement(sql2);
        PreparedStatement sentencia= control.Main.getCrearConexion().getConexion().prepareStatement(sql);
        sentencia.setInt(1,(int)jTClientes1.getValueAt(fila, 0));
        
        sentencia2.executeUpdate();
        sentencia.executeUpdate();
        
    }
    
    private void saludo(){
        try{
            Statement s = control.Main.getCrearConexion().getConexion().createStatement();
            ResultSet rs = s.executeQuery ("SELECT getNombreAgenteSesion()");
            
            String nombre = "";
            
            while(rs.next()){
                nombre += rs.getString(1);
            }
            
            labelSaludo.setText(labelSaludo.getText() + nombre + "!");
            
        }catch (SQLException e){
            System.out.println(e);
        }
    }
    
    private void insertMetasTable(JTable tabla1){
        String[] columnas = {"Mision","Tu avance","Meta","Estado","Fecha de Inicio","Fecha de Cierre"};
        DefaultTableModel dtm = new DefaultTableModel(null, columnas){
            @Override
            public boolean isCellEditable(int row, int column) {
                if(column == 6){
                    return true;
                }
                return false;
            }
            
        };
        
        try{
            Statement s = control.Main.getCrearConexion().getConexion().createStatement();
            ResultSet rs = s.executeQuery ("CALL getMetasAgente()");
            
            while(rs.next()){
                String[] filas = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),
                    rs.getString(5),rs.getString(6)};
                dtm.addRow(filas);
            }
        }catch(SQLException e){
            System.out.println(e);
        }
        
        tabla1.setModel(dtm);
    }
    
    
    private void insertHistorialTable(JTable tabla1){
        String[] columnas = {"ID Cliente","ID Factura","ID Detalle Factura","Factura Unidades", "Factura Total","Fecha de Compra","Cliente Correo Principal"};
        DefaultTableModel dtm = new DefaultTableModel(null, columnas){
            @Override
            public boolean isCellEditable(int row, int column) {
                if(column == 7){
                    return true;
                }
                return false;
            }
            
        };
        
        try{
            Statement s = control.Main.getCrearConexion().getConexion().createStatement();
            ResultSet rs = s.executeQuery ("SELECT getIDAgente()");
            
            Integer id = null;
            
            while(rs.next()){
                id = rs.getInt(1);
            }

            s = control.Main.getCrearConexion().getConexion().createStatement();
            rs = s.executeQuery ("CALL VENDEDOR_HISTORIAL(" + id + ")");
            
            while(rs.next()){
                String[] filas = {rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),
                    "$ "+rs.getString(6),rs.getString(7), rs.getString(8)};
                dtm.addRow(filas);
            }
        }catch(SQLException e){
            System.out.println(e);
        }
        
        tabla1.setModel(dtm);
    }
    
    private void createTableBusqueda(JTable tabla1, String nombre){
        String[] columnas = {"ID Cliente","Nombre Comercial"};
        DefaultTableModel dtm = new DefaultTableModel(null, columnas){
            @Override
            public boolean isCellEditable(int row, int column) {
                if(column == 2){
                    return true;
                }
                return false;
            }
            
        };
        
        try{
            Statement s = control.Main.getCrearConexion().getConexion().createStatement();
            //ResultSet rs = s.executeQuery ("SELECT getIdCliente("+'"'+nombre+'"'+")");
            
            ResultSet rs = s.executeQuery ("CALL getIdCliente("+'"'+nombre+'"'+")");
            labelRespuestaBusqueda.setText("Se han encontrado las siguientes coincidencias: ");
            
            while(rs.next()){
                String[] filas = {rs.getString(1), rs.getString(2)};
                dtm.addRow(filas);
            }
            
        }catch(SQLException e){
            System.out.println(e);
        }
        
        tabla1.setModel(dtm);
    }
    
    private void createTablaProductos(JTable tabla1){
        String[] columnas = {"Codigo Producto","Nombre Producto","Marca" ,"Unidades","Precio Unitario","Precio Secundario"};
        DefaultTableModel dtm = new DefaultTableModel(null, columnas){
            @Override
            public boolean isCellEditable(int row, int column) {
                if(column == 6){
                    return true;
                }
                return false;
            }
            
        };
        
        try{
            Statement s = control.Main.getCrearConexion().getConexion().createStatement();
            ResultSet rs = s.executeQuery ("CALL getProductos()");
            
            while(rs.next()){              
                String[] filas = {rs.getString(1), rs.getString(2),rs.getString(3),rs.getString(4)
                        ,"$ "+rs.getString(5),"$ "+rs.getString(6)};
                dtm.addRow(filas);         
            }
            
        }catch(SQLException e){
            System.out.println(e);
        }
        
        tabla1.setModel(dtm);
    }
    
    private void consultarPreguntas(JTable tabla1){
        String[] columnas = {"ID Pregunta", "ID Llamada", "Codigo Agente", "ID Cliente", "Nombre Cliente","Detalle Pregunta", "Canal",
            "Estado","Fecha Pregunta","Fecha Llamada", "Tiempo de Espera", "Servicio", "Estado",
            "Tiempo de Conversacion", "Satisfaccion", "Resolucion"};
        DefaultTableModel dtm = new DefaultTableModel(null, columnas){
            @Override
            public boolean isCellEditable(int row, int column) {
                if(column == 14){
                    return true;
                }
                return false;
            }
            
        };
        
        try{
            int clId = 0;
            if(!textCodCliente.getText().equals(""))
                clId = Integer.parseInt(textCodCliente.getText());
            Statement s = control.Main.getCrearConexion().getConexion().createStatement();
            ResultSet rs = s.executeQuery ("CALL getLlamadasCliente("+clId+")");
            
            while(rs.next()){              
                String[] filas = {rs.getString(4), rs.getString(3),rs.getString(2),rs.getString(1), rs.getString(24)
                        ,rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8)
                , rs.getString(9), rs.getString(10), rs.getString(11), rs.getString(12), rs.getString(13)
                , rs.getString(14), rs.getString(15)};
                dtm.addRow(filas);         
            }
            
        }catch(SQLException e){
            System.out.println(e);
        }
        
        tabla1.setModel(dtm);
    }
    
    private void colocarEstadisticas(){
        try{
            Statement s = control.Main.getCrearConexion().getConexion().createStatement();
            ResultSet rs = s.executeQuery ("SELECT getIDAgente()");
            
            Integer id = null;
            
            while(rs.next()){
                id = rs.getInt(1);
            }
            
            rs = s.executeQuery ("CALL VENDEDOR_VENTAS_MONTO("+id+")");
            
            String resultado = "";
            while(rs.next()){
                resultado += rs.getString(2);
            }
            
            textVentasTotales.setText("$ " + resultado);
            
            rs = s.executeQuery ("CALL VENDEDOR_VENTAS_TASA("+id+")");
            
            String resultado2 = "";
            while(rs.next()){
                resultado2 += rs.getString(2);
            }
            
            textTasaVenta.setText(resultado2 + " %");
            
            rs = s.executeQuery ("CALL VENDEDOR_VENTAS_PROMEDIO("+id+")");
            
            String resultado3 = "";
            while(rs.next()){
                resultado3 += rs.getString(2);
            }
            
            textPromedioVentas.setText("$ " + resultado3);
            
        }catch(SQLException e){
            System.out.println(e);
        }
    }
    
    private void agregarRespuesta(){
        int fila = tablaPreguntas.getSelectedRow();
        if(fila == -1){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Selecciona un registro primero", 
                    "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        AgenteAgregarRespuesta ventanaRespuesta1 = new AgenteAgregarRespuesta();
        ventanaRespuesta1.setVisible(true);
        
        ventanaRespuesta1.setData(Integer.parseInt(tablaPreguntas.getValueAt(fila, 0).toString()),
        Integer.parseInt(tablaPreguntas.getValueAt(fila, 2).toString()), Integer.parseInt(tablaPreguntas.getValueAt(fila, 1).toString()));
    }
    
    private boolean verificarHora(String hora){
        String[] formatHora = hora.split(":");
        if(Integer.parseInt(formatHora[1]) > 59 || Integer.parseInt(formatHora[2]) > 59)
            return false;  
        return true;
    }
    
    private void verRegistroCompleto(){
        int fila = tablaPreguntas.getSelectedRow();
        if(fila == -1){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Selecciona un registro primero", 
                    "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Ventana_Pregunta_Respuesta ventanaPregResp1 = new Ventana_Pregunta_Respuesta();
        ventanaPregResp1.mostrarInformacion(Integer.parseInt(tablaPreguntas.getValueAt(fila,1).toString()),
                Integer.parseInt(tablaPreguntas.getValueAt(fila,0).toString()));
        ventanaPregResp1.setVisible(true);
        
    }
    
    
}
