package GUI;

import java.math.BigDecimal;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Types;
import javax.swing.JOptionPane;
import javax.swing.JTable;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aldo
 */
public class Productos_Form extends javax.swing.JFrame{
    
    JTable t_productos;
    private Connection cnx;

    /**
     * Creates new form Productos_Form
     */
    public Productos_Form(JTable productos) {
        initComponents();
        this.t_productos=productos;
    }

    Productos_Form(Connection coneccion) {
        initComponents();
        cnx = coneccion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Tf_nombre_producto = new LIB.FSTexFieldMD();
        fSLabel21 = new LIB.FSLabel();
        fSLabel22 = new LIB.FSLabel();
        fSLabel23 = new LIB.FSLabel();
        fSLabel24 = new LIB.FSLabel();
        Tf_especificacion_producto = new LIB.FSTexFieldMD();
        Tf_Marca_producto = new LIB.FSTexFieldMD();
        Tf_Unidades_producto = new LIB.FSTexFieldMD();
        fSLabel25 = new LIB.FSLabel();
        Tf_precio_unitario_producto = new LIB.FSTexFieldMD();
        fSButtonMD1 = new LIB.FSButtonMD();
        fSLabel26 = new LIB.FSLabel();
        Tf_codigo_producto = new LIB.FSTexFieldMD();
        fSLabel27 = new LIB.FSLabel();
        Tf_categoria_producto = new LIB.FSTexFieldMD();
        fSLabel28 = new LIB.FSLabel();
        Tf_precio_secundario_producto = new LIB.FSTexFieldMD();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));

        Tf_nombre_producto.setForeground(new java.awt.Color(0, 204, 204));
        Tf_nombre_producto.setBordeColorFocus(new java.awt.Color(0, 204, 204));

        fSLabel21.setBorder(null);
        fSLabel21.setText("Unidades");

        fSLabel22.setBorder(null);
        fSLabel22.setText("Código");

        fSLabel23.setBorder(null);
        fSLabel23.setText("Marca");

        fSLabel24.setBorder(null);
        fSLabel24.setText("Precio secundario");

        Tf_especificacion_producto.setForeground(new java.awt.Color(0, 204, 204));
        Tf_especificacion_producto.setBordeColorFocus(new java.awt.Color(0, 204, 204));

        Tf_Marca_producto.setForeground(new java.awt.Color(0, 204, 204));
        Tf_Marca_producto.setBordeColorFocus(new java.awt.Color(0, 204, 204));
        Tf_Marca_producto.setSoloLetras(true);

        Tf_Unidades_producto.setForeground(new java.awt.Color(0, 204, 204));
        Tf_Unidades_producto.setBordeColorFocus(new java.awt.Color(0, 204, 204));
        Tf_Unidades_producto.setSoloNumeros(true);

        fSLabel25.setBorder(null);
        fSLabel25.setText("Precio unitario");

        Tf_precio_unitario_producto.setForeground(new java.awt.Color(0, 204, 204));
        Tf_precio_unitario_producto.setBordeColorFocus(new java.awt.Color(0, 204, 204));
        Tf_precio_unitario_producto.setSoloNumeros(true);

        fSButtonMD1.setText("Agregar producto");
        fSButtonMD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fSButtonMD1MouseClicked(evt);
            }
        });

        fSLabel26.setBorder(null);
        fSLabel26.setText("Nombre");

        Tf_codigo_producto.setForeground(new java.awt.Color(0, 204, 204));
        Tf_codigo_producto.setBordeColorFocus(new java.awt.Color(0, 204, 204));
        Tf_codigo_producto.setSoloNumeros(true);

        fSLabel27.setBorder(null);
        fSLabel27.setText("Categoría");

        Tf_categoria_producto.setForeground(new java.awt.Color(0, 204, 204));
        Tf_categoria_producto.setBordeColorFocus(new java.awt.Color(0, 204, 204));

        fSLabel28.setBorder(null);
        fSLabel28.setText("Especificación");

        Tf_precio_secundario_producto.setForeground(new java.awt.Color(0, 204, 204));
        Tf_precio_secundario_producto.setBordeColorFocus(new java.awt.Color(0, 204, 204));
        Tf_precio_secundario_producto.setSoloNumeros(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(fSButtonMD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fSLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fSLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fSLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fSLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fSLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fSLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fSLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fSLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tf_especificacion_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_Marca_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_Unidades_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_precio_unitario_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_codigo_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_precio_secundario_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_categoria_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tf_codigo_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fSLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tf_Marca_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fSLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_Unidades_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_precio_unitario_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_precio_secundario_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_categoria_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fSLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_especificacion_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(fSButtonMD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fSButtonMD1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fSButtonMD1MouseClicked
        // TODO add your handling code here:
        agregar_producto();
        

    }//GEN-LAST:event_fSButtonMD1MouseClicked

    /**
     * @param args the command line arguments
     */
    
    private void agregar_producto(){
        
        try {
            String sql = "{call insertar_producto(?,?,?,?,?,?,?,?,?)}";
            
            CallableStatement sentencia= cnx.prepareCall(sql);
            PreparedStatement comprobacion = cnx.prepareStatement("SELECT @var");
            
            sentencia.setInt("Prod_cod", Integer.parseInt (Tf_codigo_producto.getText()));
            sentencia.setString("Prod_nombre", Tf_nombre_producto.getText());
            sentencia.setString("Prod_marca",Tf_Marca_producto.getText());
            sentencia.setInt("Prod_unidades", Integer.parseInt (Tf_Unidades_producto.getText()));
            String valor = Tf_precio_unitario_producto.getText();
            double valor_double = Double.parseDouble(valor);
            float valor_float = Float.parseFloat(valor);
            sentencia.setDouble("Prod_precio_unit",  valor_float );
            
            String valor2 =  Tf_precio_secundario_producto.getText();
            double valor_double2 = Double.parseDouble(valor2);
            float valor_float2 = Float.parseFloat(valor);
            sentencia.setDouble("Prod_precio_sec",  valor_float2 );
            
            sentencia.setString("Categoria_IN", Tf_categoria_producto.getText());
            sentencia.setString("Especificacion", Tf_especificacion_producto.getText());
            sentencia.execute();
            
            Boolean respuesta = sentencia.getBoolean("RESPUESTA");
            
            if (!respuesta){
                JOptionPane.showMessageDialog(null, "La Categpría "+Tf_categoria_producto.getText()+" no se encuentra registrada, por favor agreguela.");
                Categoria_form ct = new Categoria_form(Tf_categoria_producto.getText(),Tf_Unidades_producto.getText(),Integer.parseInt(Tf_codigo_producto.getText()), cnx);
                ct.setVisible(true);
                
            }
            
            System.out.println("Inserción de producto con exito");
            super.dispose();
            JOptionPane.showMessageDialog(null, "Producto "+Tf_nombre_producto.getText()+" creado con exito.");
        } catch (SQLException ex) {
            Logger.getLogger(Cl_form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSTexFieldMD Tf_Marca_producto;
    private LIB.FSTexFieldMD Tf_Unidades_producto;
    private LIB.FSTexFieldMD Tf_categoria_producto;
    private LIB.FSTexFieldMD Tf_codigo_producto;
    private LIB.FSTexFieldMD Tf_especificacion_producto;
    private LIB.FSTexFieldMD Tf_nombre_producto;
    private LIB.FSTexFieldMD Tf_precio_secundario_producto;
    private LIB.FSTexFieldMD Tf_precio_unitario_producto;
    private LIB.FSButtonMD fSButtonMD1;
    private LIB.FSLabel fSLabel21;
    private LIB.FSLabel fSLabel22;
    private LIB.FSLabel fSLabel23;
    private LIB.FSLabel fSLabel24;
    private LIB.FSLabel fSLabel25;
    private LIB.FSLabel fSLabel26;
    private LIB.FSLabel fSLabel27;
    private LIB.FSLabel fSLabel28;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
